-- Seed: Premier League 2025/26 Current Squads
-- ~200 players across all 20 clubs (skips players already seeded in seed_ofta_person_footballers_pl.sql)
-- Column semantics: see data_products/docs/celebrity_column_semantics.md

INSERT INTO ofta_prod.ofta_person (
    full_name, date_of_birth, star_sign,
    primary_category, secondary_category,
    nationality, gender,
    attr_desc_1, attr_value_1,
    attr_desc_2, attr_value_2,
    attr_desc_3, attr_value_3,
    attr_desc_4, attr_value_4,
    attr_desc_5, attr_value_5,
    attr_desc_6, attr_value_6,
    attr_desc_7, attr_value_7,
    popularity_score, is_active
) VALUES

-- ─── ARSENAL ──────────────────────────────────────────────────────────────────

('David Raya',
 '1995-09-15', 'Virgo', 'Footballer', 'Premier League', 'Spanish', 'Male',
 'Nationality', ARRAY['Spanish'], 'Clubs', ARRAY['Arsenal', 'Brentford', 'Blackburn Rovers'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['Won PL Golden Glove 2023–24 — best save percentage in the league'],
 'Career Moment', ARRAY['Joined Arsenal on loan then permanently from Brentford in 2024'],
 'Notable Fact', ARRAY['Displaced Aaron Ramsdale as first choice within months of arriving'],
 76.00, TRUE),

('Ben White',
 '1997-10-08', 'Libra', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Arsenal', 'Brighton', 'Leeds United'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Back', 'Centre Back'],
 'Record / Trophy', ARRAY['Two consecutive top-four finishes with Arsenal 2022–24'],
 'Career Moment', ARRAY['Withdrew from England''s 2022 World Cup squad for personal reasons'],
 'Notable Fact', ARRAY['Converted from centre-back to right-back by Mikel Arteta'],
 77.00, TRUE),

('Gabriel Magalhaes',
 '1997-12-19', 'Sagittarius', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 'Nationality', ARRAY['Brazilian'], 'Clubs', ARRAY['Arsenal', 'Lille', 'Dinamo Zagreb'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['Consecutive PL title challenges with Arsenal 2022–24'],
 'Career Moment', ARRAY['Signed for £27m from Lille in 2020 — quickly became a fan favourite'],
 'Notable Fact', ARRAY['Known for his aggressive style and goals from set pieces'],
 80.00, TRUE),

('Jurrien Timber',
 '2001-06-17', 'Gemini', 'Footballer', 'Premier League', 'Dutch', 'Male',
 'Nationality', ARRAY['Dutch'], 'Clubs', ARRAY['Arsenal', 'Ajax'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Back', 'Centre Back'],
 'Record / Trophy', ARRAY['Champions League finalist with Ajax in 2019 as a youth player'],
 'Career Moment', ARRAY['Missed almost all of 2023–24 with ACL injury on debut vs Nottm Forest'],
 'Notable Fact', ARRAY['Signed from Ajax for £34m in 2023 — returned to form in 2024–25'],
 75.00, TRUE),

('Riccardo Calafiori',
 '2002-05-19', 'Taurus', 'Footballer', 'Premier League', 'Italian', 'Male',
 'Nationality', ARRAY['Italian'], 'Clubs', ARRAY['Arsenal', 'Bologna', 'Basel'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back', 'Left Back'],
 'Record / Trophy', ARRAY['Euro 2024 winner with Italy'],
 'Career Moment', ARRAY['Signed by Arsenal for £42m from Bologna after standout Serie A season'],
 'Notable Fact', ARRAY['Became one of Europe''s most sought-after defenders aged just 22'],
 76.00, TRUE),

('Thomas Partey',
 '1993-06-13', 'Gemini', 'Footballer', 'Premier League', 'Ghanaian', 'Male',
 'Nationality', ARRAY['Ghanaian'], 'Clubs', ARRAY['Arsenal', 'Atletico Madrid'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Defensive Midfielder'],
 'Record / Trophy', ARRAY['Three La Liga titles and Europa League winner with Atletico Madrid'],
 'Career Moment', ARRAY['Signed on deadline day 2020 for £45m — activating his release clause'],
 'Notable Fact', ARRAY['Injury-prone but dominant when fit — Arsenal''s key ball-winner'],
 77.00, TRUE),

('Kai Havertz',
 '1999-06-11', 'Gemini', 'Footballer', 'Premier League', 'German', 'Male',
 'Nationality', ARRAY['German'], 'Clubs', ARRAY['Arsenal', 'Chelsea', 'Bayer Leverkusen'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Forward', 'Attacking Midfielder'],
 'Record / Trophy', ARRAY['Champions League winner with Chelsea in 2021 — scored the winning goal'],
 'Career Moment', ARRAY['Moved to Arsenal for £65m in 2023 after an inconsistent Chelsea spell'],
 'Notable Fact', ARRAY['Reinvented as a false nine by Arteta — scored winner vs Man City in 2024'],
 80.00, TRUE),

('Leandro Trossard',
 '1994-12-04', 'Sagittarius', 'Footballer', 'Premier League', 'Belgian', 'Male',
 'Nationality', ARRAY['Belgian'], 'Clubs', ARRAY['Arsenal', 'Brighton', 'Genk'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Winger', 'Forward'],
 'Record / Trophy', ARRAY['Consistent contributor to Arsenal''s title challenges 2022–24'],
 'Career Moment', ARRAY['Scored a hat-trick for Brighton vs Liverpool in 2022 — match ended 3-3'],
 'Notable Fact', ARRAY['Signed for £27m from Brighton in January 2023'],
 76.00, TRUE),

('Jorginho',
 '1991-12-20', 'Sagittarius', 'Footballer', 'Premier League', 'Italian', 'Male',
 'Nationality', ARRAY['Italian', 'Brazilian'], 'Clubs', ARRAY['Arsenal', 'Chelsea', 'Napoli'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Defensive Midfielder', 'Central Midfielder'],
 'Record / Trophy', ARRAY['Champions League winner with Chelsea 2021 and Euro 2020 winner with Italy'],
 'Career Moment', ARRAY['Won Euro 2020 and the Champions League in the same calendar year'],
 'Notable Fact', ARRAY['Known for his unique penalty technique — always sends GKs the wrong way'],
 75.00, TRUE),

-- ─── CHELSEA ──────────────────────────────────────────────────────────────────

('Robert Sanchez',
 '1997-11-18', 'Scorpio', 'Footballer', 'Premier League', 'Spanish', 'Male',
 'Nationality', ARRAY['Spanish'], 'Clubs', ARRAY['Chelsea', 'Brighton', 'Levante'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['Part of Chelsea''s squad rebuild under new ownership from 2022'],
 'Career Moment', ARRAY['Signed by Chelsea for £25m from Brighton in 2023'],
 'Notable Fact', ARRAY['Spain international competing with Unai Simon for the national shirt'],
 70.00, TRUE),

('Reece James',
 '1999-12-08', 'Sagittarius', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Chelsea'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Back'],
 'Record / Trophy', ARRAY['Champions League winner with Chelsea in 2021'],
 'Career Moment', ARRAY['Named Chelsea captain — a one-club player through the academy'],
 'Notable Fact', ARRAY['Sister Lauren James also plays for Chelsea and England Women'],
 82.00, TRUE),

('Wesley Fofana',
 '2000-12-17', 'Sagittarius', 'Footballer', 'Premier League', 'French', 'Male',
 'Nationality', ARRAY['French', 'Ivorian'], 'Clubs', ARRAY['Chelsea', 'Leicester City', 'Saint-Etienne'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['Part of Chelsea''s squad in the post-Abramovich rebuild era'],
 'Career Moment', ARRAY['Signed for £70m from Leicester in 2022 — one of the most expensive defenders ever'],
 'Notable Fact', ARRAY['Suffered horrific leg break vs Villarreal in pre-season 2021'],
 74.00, TRUE),

('Levi Colwill',
 '2003-03-26', 'Aries', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Chelsea', 'Brighton'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back', 'Left Back'],
 'Record / Trophy', ARRAY['Chelsea academy product cementing himself as a first-team regular'],
 'Career Moment', ARRAY['Recalled from Brighton loan and became Chelsea''s first-choice CB'],
 'Notable Fact', ARRAY['England Under-21 international tipped for senior call-up'],
 73.00, TRUE),

('Marc Cucurella',
 '1998-07-22', 'Cancer', 'Footballer', 'Premier League', 'Spanish', 'Male',
 'Nationality', ARRAY['Spanish'], 'Clubs', ARRAY['Chelsea', 'Brighton', 'Getafe', 'Barcelona'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Back'],
 'Record / Trophy', ARRAY['Euro 2024 winner with Spain'],
 'Career Moment', ARRAY['Signed for £62m by Chelsea from Brighton in 2022'],
 'Notable Fact', ARRAY['Famous for his wild curly hair — recognised instantly on the pitch'],
 74.00, TRUE),

('Malo Gusto',
 '2003-05-19', 'Taurus', 'Footballer', 'Premier League', 'French', 'Male',
 'Nationality', ARRAY['French'], 'Clubs', ARRAY['Chelsea', 'Lyon'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Back'],
 'Record / Trophy', ARRAY['France Under-21 international breaking through at senior level'],
 'Career Moment', ARRAY['Signed from Lyon in 2023 — displaced Reece James during injury spells'],
 'Notable Fact', ARRAY['Rapid overlapping right back — one of the fastest in the PL'],
 71.00, TRUE),

('Moises Caicedo',
 '2001-11-02', 'Scorpio', 'Footballer', 'Premier League', 'Ecuadorian', 'Male',
 'Nationality', ARRAY['Ecuadorian'], 'Clubs', ARRAY['Chelsea', 'Brighton', 'Independiente del Valle'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Defensive Midfielder'],
 'Record / Trophy', ARRAY['British and world transfer record fee of £115m paid by Chelsea in 2023'],
 'Career Moment', ARRAY['Joined Chelsea from Brighton for a record fee after rejecting Liverpool'],
 'Notable Fact', ARRAY['Ecuador''s most expensive player ever — key for national team at World Cup'],
 80.00, TRUE),

('Enzo Fernandez',
 '2001-01-17', 'Capricorn', 'Footballer', 'Premier League', 'Argentine', 'Male',
 'Nationality', ARRAY['Argentine'], 'Clubs', ARRAY['Chelsea', 'Benfica', 'River Plate'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Central Midfielder'],
 'Record / Trophy', ARRAY['2022 FIFA World Cup winner with Argentina — named Young Player of the Tournament'],
 'Career Moment', ARRAY['Signed by Chelsea for £107m in January 2023 — a British record at the time'],
 'Notable Fact', ARRAY['Faced controversy over a video posted after Argentina''s Copa America win 2024'],
 82.00, TRUE),

('Romeo Lavia',
 '2004-01-06', 'Capricorn', 'Footballer', 'Premier League', 'Belgian', 'Male',
 'Nationality', ARRAY['Belgian'], 'Clubs', ARRAY['Chelsea', 'Southampton', 'Manchester City'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Defensive Midfielder'],
 'Record / Trophy', ARRAY['Signed by Chelsea for £58m despite a serious injury-plagued first season'],
 'Career Moment', ARRAY['Suffered multiple injuries in his debut Chelsea season — yet to fulfil potential'],
 'Notable Fact', ARRAY['Man City academy product sold to Southampton — Chelsea paid a premium to sign him'],
 72.00, TRUE),

('Christopher Nkunku',
 '1997-11-14', 'Scorpio', 'Footballer', 'Premier League', 'French', 'Male',
 'Nationality', ARRAY['French', 'Congolese'], 'Clubs', ARRAY['Chelsea', 'RB Leipzig', 'Paris Saint-Germain'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Forward', 'Attacking Midfielder'],
 'Record / Trophy', ARRAY['Bundesliga Player of the Season 2021–22 — 35 goals in all competitions'],
 'Career Moment', ARRAY['Signed by Chelsea for £52m but suffered ACL injury in pre-season 2023'],
 'Notable Fact', ARRAY['France international who took time to adapt after injury disrupted his start'],
 78.00, TRUE),

('Nicolas Jackson',
 '2001-06-20', 'Gemini', 'Footballer', 'Premier League', 'Senegalese', 'Male',
 'Nationality', ARRAY['Senegalese'], 'Clubs', ARRAY['Chelsea', 'Villarreal', 'Kas Eupen'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Forward'],
 'Record / Trophy', ARRAY['17 Premier League goals in debut Chelsea season 2023–24'],
 'Career Moment', ARRAY['Signed from Villarreal for £32m — became Chelsea''s first-choice striker'],
 'Notable Fact', ARRAY['Senegal international with an eye for goal despite a controversial finish style'],
 75.00, TRUE),

('Pedro Neto',
 '2000-03-09', 'Pisces', 'Footballer', 'Premier League', 'Portuguese', 'Male',
 'Nationality', ARRAY['Portuguese'], 'Clubs', ARRAY['Chelsea', 'Wolves', 'Lazio', 'Braga'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Winger'],
 'Record / Trophy', ARRAY['Signed by Chelsea for £54m from Wolves in 2024'],
 'Career Moment', ARRAY['Was one of the PL''s most exciting wingers at Wolves before the move'],
 'Notable Fact', ARRAY['Portugal international — injuries limited him at Wolves but pace is elite'],
 76.00, TRUE),

-- ─── LIVERPOOL ────────────────────────────────────────────────────────────────

('Andy Robertson',
 '1994-03-11', 'Pisces', 'Footballer', 'Premier League', 'Scottish', 'Male',
 'Nationality', ARRAY['Scottish'], 'Clubs', ARRAY['Liverpool', 'Hull City', 'Dundee United'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Back'],
 'Record / Trophy', ARRAY['2019 Champions League and 2020 Premier League winner with Liverpool'],
 'Career Moment', ARRAY['Signed from Hull City for just £8m in 2017 — one of Klopp''s best signings'],
 'Notable Fact', ARRAY['Scotland captain — first player to reach 60 caps for Scotland as captain'],
 82.00, TRUE),

('Ibrahima Konate',
 '1999-05-25', 'Gemini', 'Footballer', 'Premier League', 'French', 'Male',
 'Nationality', ARRAY['French', 'Malian'], 'Clubs', ARRAY['Liverpool', 'RB Leipzig', 'Sochaux'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['2022 FA Cup and League Cup double winner with Liverpool'],
 'Career Moment', ARRAY['Signed from RB Leipzig for £36m in 2021 — exceptional in cup runs'],
 'Notable Fact', ARRAY['Dominant in the air — one of the most physically imposing CBs in the PL'],
 78.00, TRUE),

('Joe Gomez',
 '1997-05-23', 'Gemini', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English', 'Gambian'], 'Clubs', ARRAY['Liverpool', 'Charlton Athletic'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back', 'Right Back'],
 'Record / Trophy', ARRAY['2019 Champions League and 2020 Premier League winner with Liverpool'],
 'Career Moment', ARRAY['Suffered multiple serious injuries that hampered his progression at Liverpool'],
 'Notable Fact', ARRAY['Versatile defender who can play across the entire back line'],
 74.00, TRUE),

('Conor Bradley',
 '2003-07-09', 'Cancer', 'Footballer', 'Premier League', 'Northern Irish', 'Male',
 'Nationality', ARRAY['Northern Irish'], 'Clubs', ARRAY['Liverpool', 'Bolton Wanderers'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Back'],
 'Record / Trophy', ARRAY['Emerged as Liverpool''s first-choice right back in 2024–25'],
 'Career Moment', ARRAY['Scored and assisted multiple times vs Chelsea in January 2024 — standout display'],
 'Notable Fact', ARRAY['Northern Ireland''s most exciting young player — stepped up after Trent left'],
 73.00, TRUE),

('Alexis Mac Allister',
 '1998-12-24', 'Capricorn', 'Footballer', 'Premier League', 'Argentine', 'Male',
 'Nationality', ARRAY['Argentine'], 'Clubs', ARRAY['Liverpool', 'Brighton', 'Boca Juniors'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Central Midfielder'],
 'Record / Trophy', ARRAY['2022 FIFA World Cup winner with Argentina'],
 'Career Moment', ARRAY['Signed from Brighton for £35m in 2023 — immediately became a key player'],
 'Notable Fact', ARRAY['Father Carlos and uncle Kevin both played professional football in Argentina'],
 81.00, TRUE),

('Dominik Szoboszlai',
 '2000-10-25', 'Scorpio', 'Footballer', 'Premier League', 'Hungarian', 'Male',
 'Nationality', ARRAY['Hungarian'], 'Clubs', ARRAY['Liverpool', 'RB Leipzig', 'RB Salzburg'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Attacking Midfielder'],
 'Record / Trophy', ARRAY['Hungary''s captain and most important player at just 24'],
 'Career Moment', ARRAY['Signed by Liverpool for £60m from RB Leipzig in 2023'],
 'Notable Fact', ARRAY['Famously scored a 96th-minute winner for Hungary vs Iceland to qualify for World Cup'],
 79.00, TRUE),

('Ryan Gravenberch',
 '2002-05-16', 'Taurus', 'Footballer', 'Premier League', 'Dutch', 'Male',
 'Nationality', ARRAY['Dutch', 'Surinamese'], 'Clubs', ARRAY['Liverpool', 'Bayern Munich', 'Ajax'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Central Midfielder', 'Defensive Midfielder'],
 'Record / Trophy', ARRAY['Transformed into one of the PL''s best midfielders in 2024–25'],
 'Career Moment', ARRAY['Struggled at Bayern Munich but reinvented himself under Slot at Liverpool'],
 'Notable Fact', ARRAY['Ajax academy product — signed by Liverpool for £34m after a difficult Bayern stint'],
 79.00, TRUE),

('Luis Diaz',
 '1997-01-13', 'Capricorn', 'Footballer', 'Premier League', 'Colombian', 'Male',
 'Nationality', ARRAY['Colombian'], 'Clubs', ARRAY['Liverpool', 'Porto', 'Barranquilla'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Winger', 'Forward'],
 'Record / Trophy', ARRAY['2022 FA Cup and League Cup double winner with Liverpool'],
 'Career Moment', ARRAY['Father kidnapped in Colombia shortly after his 2023 goal for Liverpool'],
 'Notable Fact', ARRAY['Signed for £37m from Porto in January 2022 — immediately impressed'],
 81.00, TRUE),

('Diogo Jota',
 '1996-12-04', 'Sagittarius', 'Footballer', 'Premier League', 'Portuguese', 'Male',
 'Nationality', ARRAY['Portuguese'], 'Clubs', ARRAY['Liverpool', 'Wolves', 'Atletico Madrid', 'Porto'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Forward', 'Left Winger'],
 'Record / Trophy', ARRAY['2022 FA Cup and League Cup double winner with Liverpool'],
 'Career Moment', ARRAY['Scored a hat-trick on his first Anfield start vs Atalanta in 2020'],
 'Notable Fact', ARRAY['Injury-prone but lethal in front of goal — averaged a goal every other game'],
 79.00, TRUE),

('Cody Gakpo',
 '1999-05-07', 'Taurus', 'Footballer', 'Premier League', 'Dutch', 'Male',
 'Nationality', ARRAY['Dutch', 'Ghanaian'], 'Clubs', ARRAY['Liverpool', 'PSV Eindhoven'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Forward', 'Left Winger'],
 'Record / Trophy', ARRAY['Scored in three consecutive 2022 World Cup group games for Netherlands'],
 'Career Moment', ARRAY['Signed by Liverpool for £44m in January 2023 after a superb PSV season'],
 'Notable Fact', ARRAY['Versatile attacker who improved dramatically in his second Liverpool season'],
 78.00, TRUE),

('Darwin Nunez',
 '1999-06-24', 'Cancer', 'Footballer', 'Premier League', 'Uruguayan', 'Male',
 'Nationality', ARRAY['Uruguayan'], 'Clubs', ARRAY['Liverpool', 'Benfica', 'Almeria'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Forward'],
 'Record / Trophy', ARRAY['£85m signing from Benfica — Liverpool''s biggest ever transfer at the time'],
 'Career Moment', ARRAY['Scored a hat-trick for Benfica vs Bayern Munich in the Champions League'],
 'Notable Fact', ARRAY['Infamous for missing a series of sitters in high-profile games early in career'],
 78.00, TRUE),

-- ─── MANCHESTER CITY ──────────────────────────────────────────────────────────

('Ederson',
 '1993-08-17', 'Leo', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 'Nationality', ARRAY['Brazilian'], 'Clubs', ARRAY['Manchester City', 'Benfica', 'Rio Ave'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['Six Premier League titles with Manchester City'],
 'Career Moment', ARRAY['Signed from Benfica for £35m in 2017 — transformed City''s build-up play'],
 'Notable Fact', ARRAY['Revolutionary sweeper keeper — assists from his distribution are legendary'],
 83.00, TRUE),

('Kyle Walker',
 '1990-05-28', 'Gemini', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Manchester City', 'Tottenham Hotspur', 'Sheffield United'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Back'],
 'Record / Trophy', ARRAY['Six Premier League titles with Manchester City — and the 2023 Treble'],
 'Career Moment', ARRAY['Signed from Spurs for £45m in 2017 — then the most expensive defender ever'],
 'Notable Fact', ARRAY['One of the fastest players in PL history — scientifically tested at 38.08 km/h'],
 80.00, TRUE),

('Ruben Dias',
 '1997-05-14', 'Taurus', 'Footballer', 'Premier League', 'Portuguese', 'Male',
 'Nationality', ARRAY['Portuguese'], 'Clubs', ARRAY['Manchester City', 'Benfica'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['PL Player of the Season 2020–21 — transformed Man City''s defence'],
 'Career Moment', ARRAY['Signed for £61m from Benfica in 2020 — immediate impact winning the PL'],
 'Notable Fact', ARRAY['Won four Premier League titles in five seasons at City'],
 84.00, TRUE),

('Manuel Akanji',
 '1995-07-19', 'Cancer', 'Footballer', 'Premier League', 'Swiss', 'Male',
 'Nationality', ARRAY['Swiss', 'Nigerian'], 'Clubs', ARRAY['Manchester City', 'Borussia Dortmund', 'Basel'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['2023 Treble winner with Manchester City'],
 'Career Moment', ARRAY['Signed from Dortmund for £17m in 2022 — exceptional value in an elite squad'],
 'Notable Fact', ARRAY['Switzerland captain — dual nationality with Nigerian heritage'],
 76.00, TRUE),

('Josko Gvardiol',
 '2002-01-23', 'Aquarius', 'Footballer', 'Premier League', 'Croatian', 'Male',
 'Nationality', ARRAY['Croatian'], 'Clubs', ARRAY['Manchester City', 'RB Leipzig', 'Dinamo Zagreb'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Back', 'Centre Back'],
 'Record / Trophy', ARRAY['2022 World Cup bronze medal with Croatia'],
 'Career Moment', ARRAY['Signed for £77m in 2023 — City''s record fee and a world record for a defender'],
 'Notable Fact', ARRAY['Famously tried to stop Mbappe in the 2022 World Cup — an iconic defensive duel'],
 80.00, TRUE),

('John Stones',
 '1994-05-28', 'Gemini', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Manchester City', 'Everton', 'Barnsley'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back', 'Defensive Midfielder'],
 'Record / Trophy', ARRAY['Six Premier League titles with Manchester City — and the 2023 Treble'],
 'Career Moment', ARRAY['Reinvented as a midfielder under Guardiola — unique in world football'],
 'Notable Fact', ARRAY['Signed for £47.5m from Everton in 2016 — early struggles made the fee look costly'],
 79.00, TRUE),

('Rodri',
 '1996-06-22', 'Cancer', 'Footballer', 'Premier League', 'Spanish', 'Male',
 'Nationality', ARRAY['Spanish'], 'Clubs', ARRAY['Manchester City', 'Atletico Madrid', 'Villarreal'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Defensive Midfielder'],
 'Record / Trophy', ARRAY['Ballon d''Or winner 2024 — first Man City player to win it'],
 'Career Moment', ARRAY['Scored the winning goal in the 2023 Champions League final vs Inter'],
 'Notable Fact', ARRAY['Euro 2024 winner with Spain — went unbeaten for over a year for club and country'],
 90.00, TRUE),

('Bernardo Silva',
 '1994-08-10', 'Leo', 'Footballer', 'Premier League', 'Portuguese', 'Male',
 'Nationality', ARRAY['Portuguese'], 'Clubs', ARRAY['Manchester City', 'Monaco', 'Benfica'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Midfielder', 'Winger'],
 'Record / Trophy', ARRAY['Six Premier League titles and the 2023 Champions League with Man City'],
 'Career Moment', ARRAY['Linked with Barcelona every summer but remained the heartbeat of City'],
 'Notable Fact', ARRAY['Guardiola''s most trusted midfielder — described as a "PS5 player" by his manager'],
 86.00, TRUE),

('Mateo Kovacic',
 '1994-05-06', 'Taurus', 'Footballer', 'Premier League', 'Croatian', 'Male',
 'Nationality', ARRAY['Croatian'], 'Clubs', ARRAY['Manchester City', 'Chelsea', 'Real Madrid', 'Inter Milan'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Central Midfielder'],
 'Record / Trophy', ARRAY['Champions League winner 2021 with Chelsea and 2023 with Manchester City'],
 'Career Moment', ARRAY['Won the Champions League with two different English clubs'],
 'Notable Fact', ARRAY['2018 World Cup finalist with Croatia — never booked in his first 100 PL games'],
 78.00, TRUE),

('Jeremy Doku',
 '2002-12-12', 'Sagittarius', 'Footballer', 'Premier League', 'Belgian', 'Male',
 'Nationality', ARRAY['Belgian', 'Ghanaian'], 'Clubs', ARRAY['Manchester City', 'Rennes', 'Anderlecht'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Winger'],
 'Record / Trophy', ARRAY['Signed for £55m from Rennes in 2023 — one of Europe''s most exciting dribblers'],
 'Career Moment', ARRAY['Dribbled past 5 opponents in a single run vs Wolves — went viral globally'],
 'Notable Fact', ARRAY['Belgium international at just 17 — one of the fastest wide players in the PL'],
 78.00, TRUE),

('Savinho',
 '2004-08-10', 'Leo', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 'Nationality', ARRAY['Brazilian'], 'Clubs', ARRAY['Manchester City', 'Girona', 'Atletico Mineiro'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Winger'],
 'Record / Trophy', ARRAY['Signed permanently by Man City for £33m after an outstanding Girona loan'],
 'Career Moment', ARRAY['Had 12 goals and 11 assists for Girona in 2023–24 helping them reach Champions League'],
 'Notable Fact', ARRAY['City Football Group product — developed across their global network of clubs'],
 74.00, TRUE),

-- ─── MANCHESTER UNITED ────────────────────────────────────────────────────────

('Andre Onana',
 '1996-04-02', 'Aries', 'Footballer', 'Premier League', 'Cameroonian', 'Male',
 'Nationality', ARRAY['Cameroonian'], 'Clubs', ARRAY['Manchester United', 'Inter Milan', 'Ajax'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['2023 Champions League finalist with Inter Milan'],
 'Career Moment', ARRAY['Error-prone debut Man Utd season — received public criticism from fans'],
 'Notable Fact', ARRAY['Banned for 9 months by UEFA for a doping violation before being cleared'],
 74.00, TRUE),

('Lisandro Martinez',
 '1998-01-18', 'Capricorn', 'Footballer', 'Premier League', 'Argentine', 'Male',
 'Nationality', ARRAY['Argentine'], 'Clubs', ARRAY['Manchester United', 'Ajax', 'Defensa y Justicia'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['2022 FIFA World Cup winner with Argentina'],
 'Career Moment', ARRAY['Signed for £57m from Ajax in 2022 — critics questioned his 5ft10 height for PL'],
 'Notable Fact', ARRAY['Nicknamed "The Butcher of Ajax" for his aggressive defending style'],
 80.00, TRUE),

('Harry Maguire',
 '1993-03-05', 'Pisces', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Manchester United', 'Leicester City', 'Hull City', 'Sheffield United'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['Most expensive defender in history when signed — £80m in 2019'],
 'Career Moment', ARRAY['Arrested in Mykonos 2020 — case eventually overturned on appeal'],
 'Notable Fact', ARRAY['England regular but polarising at Man Utd — endured heavy fan criticism'],
 75.00, TRUE),

('Diogo Dalot',
 '1999-03-18', 'Pisces', 'Footballer', 'Premier League', 'Portuguese', 'Male',
 'Nationality', ARRAY['Portuguese'], 'Clubs', ARRAY['Manchester United', 'AC Milan', 'Porto'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Back'],
 'Record / Trophy', ARRAY['Portugal''s first-choice right back — key in Euro 2024 campaign'],
 'Career Moment', ARRAY['Signed by José Mourinho from Porto in 2018 — became a Man Utd regular under Ten Hag'],
 'Notable Fact', ARRAY['Can play on either flank — one of Man Utd''s most consistent performers'],
 75.00, TRUE),

('Luke Shaw',
 '1995-07-12', 'Cancer', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Manchester United', 'Southampton'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Back'],
 'Record / Trophy', ARRAY['Euro 2020 finalist with England — scored the opening goal in the final'],
 'Career Moment', ARRAY['Suffered a horrific double leg break vs PSV in 2015 — remarkable comeback'],
 'Notable Fact', ARRAY['Publicly criticised by José Mourinho during his time as manager — rebuilt his career'],
 77.00, TRUE),

('Casemiro',
 '1992-02-23', 'Pisces', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 'Nationality', ARRAY['Brazilian'], 'Clubs', ARRAY['Manchester United', 'Real Madrid', 'Porto'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Defensive Midfielder'],
 'Record / Trophy', ARRAY['Five Champions League titles with Real Madrid — a serial winner'],
 'Career Moment', ARRAY['Signed by Man Utd for £70m in 2022 — stellar first season then struggled'],
 'Notable Fact', ARRAY['Won CL 3 times in a row with Real Madrid (2016, 2017, 2018)'],
 79.00, TRUE),

('Kobbie Mainoo',
 '2005-04-19', 'Aries', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English', 'Ghanaian'], 'Clubs', ARRAY['Manchester United'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Central Midfielder'],
 'Record / Trophy', ARRAY['Euro 2024 finalist with England — scored in the semi-final vs Netherlands'],
 'Career Moment', ARRAY['Scored on his first PL start in 2024 — became England''s youngest Euro finalist scorer'],
 'Notable Fact', ARRAY['Man Utd academy product — one of the most exciting English midfielders in a generation'],
 78.00, TRUE),

('Alejandro Garnacho',
 '2004-07-01', 'Cancer', 'Footballer', 'Premier League', 'Argentine', 'Male',
 'Nationality', ARRAY['Argentine', 'Spanish'], 'Clubs', ARRAY['Manchester United', 'Atletico Madrid'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Winger', 'Right Winger'],
 'Record / Trophy', ARRAY['Scored an overhead kick voted PL Goal of the Season 2023–24'],
 'Career Moment', ARRAY['Scored a late winner vs Fulham 2023 — announced himself to the PL'],
 'Notable Fact', ARRAY['Born in Spain but chose to represent Argentina — called up by Scaloni in 2022'],
 77.00, TRUE),

('Rasmus Hojlund',
 '2003-02-04', 'Aquarius', 'Footballer', 'Premier League', 'Danish', 'Male',
 'Nationality', ARRAY['Danish'], 'Clubs', ARRAY['Manchester United', 'Atalanta', 'Sturm Graz'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Forward'],
 'Record / Trophy', ARRAY['Signed by Man Utd for £72m from Atalanta in 2023'],
 'Career Moment', ARRAY['Scored in 5 consecutive PL games in late 2023 — the youngest to do so in the competition'],
 'Notable Fact', ARRAY['Holds a Guinness World Record for youngest player to score in 5 straight PL games'],
 75.00, TRUE),

('Mason Mount',
 '1999-01-10', 'Capricorn', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Manchester United', 'Chelsea', 'Derby County'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Attacking Midfielder', 'Central Midfielder'],
 'Record / Trophy', ARRAY['Champions League winner with Chelsea in 2021'],
 'Career Moment', ARRAY['Signed by Man Utd for £60m in 2023 — repeated injury problems frustrated his debut season'],
 'Notable Fact', ARRAY['Chelsea academy product from age 6 — left after 11 years to join United'],
 75.00, TRUE),

-- ─── TOTTENHAM HOTSPUR ────────────────────────────────────────────────────────

('Guglielmo Vicario',
 '1996-10-07', 'Libra', 'Footballer', 'Premier League', 'Italian', 'Male',
 'Nationality', ARRAY['Italian'], 'Clubs', ARRAY['Tottenham Hotspur', 'Empoli', 'Cagliari'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['Italy''s backup keeper — consistent performer in the PL'],
 'Career Moment', ARRAY['Signed by Spurs for £17m from Empoli in 2023 — exceeded expectations'],
 'Notable Fact', ARRAY['Came through the Juventus academy before finding his path via loan spells'],
 72.00, TRUE),

('Pedro Porro',
 '1999-09-13', 'Virgo', 'Footballer', 'Premier League', 'Spanish', 'Male',
 'Nationality', ARRAY['Spanish'], 'Clubs', ARRAY['Tottenham Hotspur', 'Sporting CP', 'Manchester City'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Back'],
 'Record / Trophy', ARRAY['Signed permanently by Spurs in 2023 after strong loan spell from Man City'],
 'Career Moment', ARRAY['Became Spurs'' first-choice right back — known for his driving forward runs'],
 'Notable Fact', ARRAY['Spain international — developed under Guardiola at Man City before finding his path'],
 74.00, TRUE),

('Cristian Romero',
 '1998-04-27', 'Taurus', 'Footballer', 'Premier League', 'Argentine', 'Male',
 'Nationality', ARRAY['Argentine'], 'Clubs', ARRAY['Tottenham Hotspur', 'Atalanta', 'Juventus', 'Genoa'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['2022 FIFA World Cup winner with Argentina'],
 'Career Moment', ARRAY['Signed permanently by Spurs for £42.5m from Atalanta in 2022'],
 'Notable Fact', ARRAY['Aggressive and combative — one of the most physical centre backs in the PL'],
 80.00, TRUE),

('Micky van de Ven',
 '2001-04-19', 'Aries', 'Footballer', 'Premier League', 'Dutch', 'Male',
 'Nationality', ARRAY['Dutch'], 'Clubs', ARRAY['Tottenham Hotspur', 'Wolfsburg', 'FC Volendam'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['One of the fastest defenders ever recorded — clocked at 36.9 km/h in a sprint'],
 'Career Moment', ARRAY['Signed by Spurs for £43m from Wolfsburg in 2023 — immediately impressed'],
 'Notable Fact', ARRAY['Netherlands international — pace makes him unique as a modern centre back'],
 76.00, TRUE),

('Destiny Udogie',
 '2002-11-28', 'Sagittarius', 'Footballer', 'Premier League', 'Italian', 'Male',
 'Nationality', ARRAY['Italian', 'Nigerian'], 'Clubs', ARRAY['Tottenham Hotspur', 'Udinese'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Back'],
 'Record / Trophy', ARRAY['Italy Under-21 European Championship winner 2023'],
 'Career Moment', ARRAY['Signed by Spurs for £21m — loaned back to Udinese then emerged as a key player'],
 'Notable Fact', ARRAY['Born in Italy to Nigerian parents — one of the most dynamic left backs in the PL'],
 74.00, TRUE),

('Yves Bissouma',
 '1996-08-30', 'Virgo', 'Footballer', 'Premier League', 'Malian', 'Male',
 'Nationality', ARRAY['Malian'], 'Clubs', ARRAY['Tottenham Hotspur', 'Brighton', 'Lille'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Defensive Midfielder'],
 'Record / Trophy', ARRAY['Mali international — one of the most tenacious ball-winners in the PL'],
 'Career Moment', ARRAY['Signed from Brighton for £25m in 2022 after catching Spurs'' eye over multiple seasons'],
 'Notable Fact', ARRAY['Was charged with drug possession but cleared — distraction in early Spurs career'],
 74.00, TRUE),

('James Maddison',
 '1996-11-23', 'Sagittarius', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Tottenham Hotspur', 'Leicester City', 'Coventry City'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Attacking Midfielder'],
 'Record / Trophy', ARRAY['Signed for £40m from Leicester in 2023 — PL Player of the Month in first season'],
 'Career Moment', ARRAY['Scored and assisted 10+ times in first half-season at Spurs — one of the best PL starts ever'],
 'Notable Fact', ARRAY['Obsessed with darts — regularly collaborates with professional darts players'],
 81.00, TRUE),

('Dejan Kulusevski',
 '2000-04-25', 'Taurus', 'Footballer', 'Premier League', 'Swedish', 'Male',
 'Nationality', ARRAY['Swedish', 'Macedonian'], 'Clubs', ARRAY['Tottenham Hotspur', 'Juventus', 'Parma', 'Atalanta'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Winger', 'Attacking Midfielder'],
 'Record / Trophy', ARRAY['Transformed Spurs after joining on loan then permanently in 2022'],
 'Career Moment', ARRAY['Arrived at Spurs mid-season and immediately sparked a top-four run'],
 'Notable Fact', ARRAY['Sweden international of Macedonian heritage — plays with a unique directness'],
 77.00, TRUE),

('Brennan Johnson',
 '2001-05-23', 'Gemini', 'Footballer', 'Premier League', 'Welsh', 'Male',
 'Nationality', ARRAY['Welsh'], 'Clubs', ARRAY['Tottenham Hotspur', 'Nottingham Forest', 'Lincoln City'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Winger', 'Forward'],
 'Record / Trophy', ARRAY['Signed by Spurs for £47m from Nottingham Forest in 2023'],
 'Career Moment', ARRAY['Wales international — scored important goals in big Premier League games'],
 'Notable Fact', ARRAY['Son of former Wales international David Johnson'],
 74.00, TRUE),

('Dominic Solanke',
 '1997-09-14', 'Virgo', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Tottenham Hotspur', 'Bournemouth', 'Liverpool', 'Chelsea'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Forward'],
 'Record / Trophy', ARRAY['Scored 19 Premier League goals for Bournemouth in 2023–24'],
 'Career Moment', ARRAY['Signed by Spurs for £65m in 2024 — the biggest fee Spurs had paid'],
 'Notable Fact', ARRAY['England Under-20 World Cup winner 2017 — took time to fulfil potential'],
 77.00, TRUE),

('Richarlison',
 '1997-05-10', 'Taurus', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 'Nationality', ARRAY['Brazilian'], 'Clubs', ARRAY['Tottenham Hotspur', 'Everton', 'Watford'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Forward', 'Left Winger'],
 'Record / Trophy', ARRAY['Scored a stunning bicycle kick for Brazil vs Serbia at 2022 World Cup'],
 'Career Moment', ARRAY['Signed by Spurs for £60m from Everton in 2022 — injuries hampered his impact'],
 'Notable Fact', ARRAY['Extremely popular in Brazil — publicly emotional about overcoming poverty to reach the top'],
 77.00, TRUE),

-- ─── NEWCASTLE UNITED ─────────────────────────────────────────────────────────

('Nick Pope',
 '1992-04-19', 'Aries', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Newcastle United', 'Burnley', 'Charlton Athletic'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['PL Golden Glove runner-up 2022–23 — kept 14 clean sheets for Newcastle'],
 'Career Moment', ARRAY['Signed from Burnley for £10m in 2022 — immediately impressed at St James'' Park'],
 'Notable Fact', ARRAY['England''s backup keeper — consistent and reliable in goal'],
 75.00, TRUE),

('Kieran Trippier',
 '1990-09-19', 'Virgo', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Newcastle United', 'Atletico Madrid', 'Tottenham Hotspur', 'Burnley'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Back'],
 'Record / Trophy', ARRAY['La Liga winner with Atletico Madrid 2021 — key to Diego Simeone''s system'],
 'Career Moment', ARRAY['Free kick assist in 2018 World Cup semi-final for England''s goal vs Croatia'],
 'Notable Fact', ARRAY['Persuaded key signings to join Newcastle — informally acted as a club ambassador'],
 79.00, TRUE),

('Fabian Schar',
 '1991-12-20', 'Sagittarius', 'Footballer', 'Premier League', 'Swiss', 'Male',
 'Nationality', ARRAY['Swiss'], 'Clubs', ARRAY['Newcastle United', 'Deportivo La Coruna', 'Basel'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['One of the best ball-playing defenders in the PL — known for long-range goals'],
 'Career Moment', ARRAY['Scored a stunning 30-yard volley vs Everton 2021 — one of the PL goals of the season'],
 'Notable Fact', ARRAY['Switzerland international — a model of consistency under Eddie Howe'],
 74.00, TRUE),

('Dan Burn',
 '1992-05-09', 'Taurus', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Newcastle United', 'Brighton', 'Wigan Athletic'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back', 'Left Back'],
 'Record / Trophy', ARRAY['Key part of Newcastle''s Champions League qualification squad 2022–23'],
 'Career Moment', ARRAY['Born near Newcastle — fulfilled his dream to play for his hometown club in 2022'],
 'Notable Fact', ARRAY['One of the tallest outfield players in the PL at 6ft 7in'],
 72.00, TRUE),

('Bruno Guimaraes',
 '1997-11-16', 'Scorpio', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 'Nationality', ARRAY['Brazilian'], 'Clubs', ARRAY['Newcastle United', 'Lyon', 'Athletico Paranaense'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Central Midfielder'],
 'Record / Trophy', ARRAY['Newcastle''s most important player — signed record-breaking new contract in 2024'],
 'Career Moment', ARRAY['Rejected a move to Arsenal 2024 — committed to Newcastle''s project'],
 'Notable Fact', ARRAY['Brazil international and one of the best midfielders in the Premier League'],
 85.00, TRUE),

('Sandro Tonali',
 '2000-05-08', 'Taurus', 'Footballer', 'Premier League', 'Italian', 'Male',
 'Nationality', ARRAY['Italian'], 'Clubs', ARRAY['Newcastle United', 'AC Milan', 'Brescia'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Central Midfielder'],
 'Record / Trophy', ARRAY['Serie A winner with AC Milan in 2022 — named in the team of the season'],
 'Career Moment', ARRAY['Received 10-month ban for gambling offences — returned stronger in 2024'],
 'Notable Fact', ARRAY['Signed by Newcastle for £55m in 2023 — ban disrupted his debut season'],
 77.00, TRUE),

('Anthony Gordon',
 '2001-10-24', 'Scorpio', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Newcastle United', 'Everton'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Winger', 'Right Winger'],
 'Record / Trophy', ARRAY['One of the most in-form wide players in the PL 2023–24'],
 'Career Moment', ARRAY['Rejected by Liverpool in January 2024 — Newcastle refused to sell at any price'],
 'Notable Fact', ARRAY['Everton academy product signed by Newcastle for £45m in 2023'],
 79.00, TRUE),

('Joelinton',
 '1996-08-14', 'Leo', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 'Nationality', ARRAY['Brazilian'], 'Clubs', ARRAY['Newcastle United', 'Hoffenheim', 'Rapid Vienna'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Central Midfielder', 'Forward'],
 'Record / Trophy', ARRAY['Newcastle''s most improved player — transformed from striker to box-to-box midfielder'],
 'Career Moment', ARRAY['Joined Newcastle as a £40m striker and reinvented himself completely under Howe'],
 'Notable Fact', ARRAY['Struggled badly as a No.9 but thrived once moved to midfield — one of the PL''s best redemption arcs'],
 76.00, TRUE),

('Harvey Barnes',
 '1997-12-09', 'Sagittarius', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Newcastle United', 'Leicester City', 'West Brom'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Winger'],
 'Record / Trophy', ARRAY['Signed by Newcastle for £38m from Leicester in 2023'],
 'Career Moment', ARRAY['Formed a rapid wide trio alongside Isak and Gordon for Newcastle'],
 'Notable Fact', ARRAY['Pace and directness make him a nightmare for defenders — England squad contender'],
 74.00, TRUE),

-- ─── ASTON VILLA ──────────────────────────────────────────────────────────────

('Emiliano Martinez',
 '1992-09-02', 'Virgo', 'Footballer', 'Premier League', 'Argentine', 'Male',
 'Nationality', ARRAY['Argentine'], 'Clubs', ARRAY['Aston Villa', 'Arsenal', 'Getafe'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['2022 FIFA World Cup winner with Argentina — named Golden Glove'],
 'Career Moment', ARRAY['Saved 3 penalties in Copa America final 2021 — iconic glove-kissing celebration'],
 'Notable Fact', ARRAY['Known for his provocative mind games with penalty takers — and it works'],
 85.00, TRUE),

('Matty Cash',
 '1997-08-07', 'Leo', 'Footballer', 'Premier League', 'Polish', 'Male',
 'Nationality', ARRAY['Polish', 'English'], 'Clubs', ARRAY['Aston Villa', 'Nottingham Forest', 'Wigan Athletic'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Back'],
 'Record / Trophy', ARRAY['Chose to represent Poland internationally despite being English-born'],
 'Career Moment', ARRAY['Signed from Nottingham Forest for £14m in 2020 — became a Villa regular'],
 'Notable Fact', ARRAY['Poland international — one of the most attacking right backs in the PL'],
 73.00, TRUE),

('Pau Torres',
 '1997-01-16', 'Capricorn', 'Footballer', 'Premier League', 'Spanish', 'Male',
 'Nationality', ARRAY['Spanish'], 'Clubs', ARRAY['Aston Villa', 'Villarreal', 'Malaga'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['Europa League winner with Villarreal 2021 — beating Man Utd on pens'],
 'Career Moment', ARRAY['Signed by Aston Villa for £33m in 2023 — Spain international at his peak'],
 'Notable Fact', ARRAY['Calm on the ball and commanding in the air — a modern ball-playing defender'],
 76.00, TRUE),

('Ezri Konsa',
 '1997-10-23', 'Scorpio', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English', 'Angolan'], 'Clubs', ARRAY['Aston Villa', 'Brentford', 'Charlton Athletic'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['One of the most consistent centre backs in the PL — England squad regular'],
 'Career Moment', ARRAY['Signed from Brentford for £12m in 2019 — blossomed into a top-four calibre CB'],
 'Notable Fact', ARRAY['England international who started in non-league football with Charlton''s academy'],
 76.00, TRUE),

('Lucas Digne',
 '1993-07-20', 'Cancer', 'Footballer', 'Premier League', 'French', 'Male',
 'Nationality', ARRAY['French'], 'Clubs', ARRAY['Aston Villa', 'Everton', 'Barcelona', 'Roma', 'PSG'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Back'],
 'Record / Trophy', ARRAY['2018 World Cup finalist with France'],
 'Career Moment', ARRAY['Left Everton in acrimonious circumstances after a fallout with Rafa Benitez in 2022'],
 'Notable Fact', ARRAY['Crosser of the ball — his deliveries from left back are among the best in the league'],
 74.00, TRUE),

('John McGinn',
 '1994-10-18', 'Libra', 'Footballer', 'Premier League', 'Scottish', 'Male',
 'Nationality', ARRAY['Scottish'], 'Clubs', ARRAY['Aston Villa', 'Hibernian', 'St Mirren'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Central Midfielder'],
 'Record / Trophy', ARRAY['Aston Villa vice-captain — Scotland captain since 2021'],
 'Career Moment', ARRAY['Signed for just £2.75m from Hibernian in 2018 — one of the PL''s best value signings'],
 'Notable Fact', ARRAY['Goal against San Marino in 2019 — celebrated by diving into a crowd of fans'],
 76.00, TRUE),

('Amadou Onana',
 '2001-08-16', 'Leo', 'Footballer', 'Premier League', 'Belgian', 'Male',
 'Nationality', ARRAY['Belgian', 'Senegalese'], 'Clubs', ARRAY['Aston Villa', 'Everton', 'Lille', 'Hamburg'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Defensive Midfielder'],
 'Record / Trophy', ARRAY['Signed by Aston Villa for £50m from Everton in 2024'],
 'Career Moment', ARRAY['One of the tallest midfielders in the PL at 6ft 4in — dominant aerially and physically'],
 'Notable Fact', ARRAY['Belgium international — chose Belgium over Senegal where he was born'],
 75.00, TRUE),

('Youri Tielemans',
 '1997-05-07', 'Taurus', 'Footballer', 'Premier League', 'Belgian', 'Male',
 'Nationality', ARRAY['Belgian'], 'Clubs', ARRAY['Aston Villa', 'Leicester City', 'Monaco', 'Anderlecht'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Central Midfielder'],
 'Record / Trophy', ARRAY['Scored the FA Cup winning goal for Leicester City vs Chelsea in 2021'],
 'Career Moment', ARRAY['Joined Villa on a free transfer in 2023 — rediscovered form after difficult Leicester end'],
 'Notable Fact', ARRAY['His 2021 FA Cup final goal from range is one of the great Wembley moments'],
 77.00, TRUE),

('Leon Bailey',
 '1997-08-09', 'Leo', 'Footballer', 'Premier League', 'Jamaican', 'Male',
 'Nationality', ARRAY['Jamaican'], 'Clubs', ARRAY['Aston Villa', 'Bayer Leverkusen', 'Genk'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Winger', 'Left Winger'],
 'Record / Trophy', ARRAY['Signed by Aston Villa for £25m in 2021 — pace and trickery a constant threat'],
 'Career Moment', ARRAY['Scored on his PL debut as a substitute in 2021 — raised hopes that took time to fulfil'],
 'Notable Fact', ARRAY['Born in Kingston, Jamaica — adopted by his agent as a child and brought to Europe'],
 74.00, TRUE),

('Morgan Rogers',
 '2002-07-26', 'Leo', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Aston Villa', 'Middlesbrough', 'Manchester City'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Attacking Midfielder', 'Winger'],
 'Record / Trophy', ARRAY['Signed by Aston Villa for £8m from Middlesbrough in 2024 — excellent value'],
 'Career Moment', ARRAY['Emerged as one of the most exciting young English attackers in 2024–25'],
 'Notable Fact', ARRAY['Man City academy product who found his game outside the Premier League before returning'],
 73.00, TRUE),

-- ─── BRIGHTON & HOVE ALBION ───────────────────────────────────────────────────

('Bart Verbruggen',
 '2002-08-18', 'Leo', 'Footballer', 'Premier League', 'Dutch', 'Male',
 'Nationality', ARRAY['Dutch'], 'Clubs', ARRAY['Brighton', 'Anderlecht'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['Netherlands international — one of the best young keepers in Europe'],
 'Career Moment', ARRAY['Signed from Anderlecht for £18m in 2023 — quickly established himself at Brighton'],
 'Notable Fact', ARRAY['Made several high-profile saves at Euro 2024 for the Netherlands'],
 72.00, TRUE),

('Lewis Dunk',
 '1991-11-21', 'Scorpio', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Brighton'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['Brighton captain — a one-club man through their rise from League One to the PL'],
 'Career Moment', ARRAY['Led Brighton to their first ever European campaign in 2023–24'],
 'Notable Fact', ARRAY['Brighton legend — has made over 400 appearances for the club'],
 74.00, TRUE),

('Jan Paul van Hecke',
 '2000-06-08', 'Gemini', 'Footballer', 'Premier League', 'Dutch', 'Male',
 'Nationality', ARRAY['Dutch'], 'Clubs', ARRAY['Brighton', 'Blackburn Rovers'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['Netherlands international emerging as a top-level centre back'],
 'Career Moment', ARRAY['Joined Brighton as a teenager and worked through loans before breaking through'],
 'Notable Fact', ARRAY['Ball-playing CB who suits De Zerbi and later Fabian Hurzeler''s possession style'],
 72.00, TRUE),

('Pervis Estupinan',
 '1998-01-21', 'Aquarius', 'Footballer', 'Premier League', 'Ecuadorian', 'Male',
 'Nationality', ARRAY['Ecuadorian'], 'Clubs', ARRAY['Brighton', 'Villarreal', 'Osasuna'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Back'],
 'Record / Trophy', ARRAY['Ecuador''s first-choice left back — consistently among the PL''s best at his position'],
 'Career Moment', ARRAY['Signed from Villarreal for £15m — one of Brighton''s best ever pieces of business'],
 'Notable Fact', ARRAY['Rapid attacker from left back — overlapping runs make him a constant threat'],
 75.00, TRUE),

('Kaoru Mitoma',
 '1997-05-20', 'Taurus', 'Footballer', 'Premier League', 'Japanese', 'Male',
 'Nationality', ARRAY['Japanese'], 'Clubs', ARRAY['Brighton', 'Union Saint-Gilloise', 'Kawasaki Frontale'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Winger'],
 'Record / Trophy', ARRAY['Japan international — one of the most direct wingers in the Premier League'],
 'Career Moment', ARRAY['Scored a goal-line dribble vs Bournemouth 2022 that was confirmed by VAR — went viral'],
 'Notable Fact', ARRAY['Studied the biomechanics of dribbling for his university thesis'],
 78.00, TRUE),

('Joao Pedro',
 '2001-09-26', 'Libra', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 'Nationality', ARRAY['Brazilian'], 'Clubs', ARRAY['Brighton', 'Watford', 'Fluminense'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Forward', 'Attacking Midfielder'],
 'Record / Trophy', ARRAY['13 Premier League goals in 2023–24 — Brighton''s top scorer'],
 'Career Moment', ARRAY['Came through at Watford before Brighton paid £30m to bring him to the top flight'],
 'Notable Fact', ARRAY['Brazil international and one of the PL''s most clinical young forwards'],
 75.00, TRUE),

('Simon Adingra',
 '2002-01-27', 'Aquarius', 'Footballer', 'Premier League', 'Ivorian', 'Male',
 'Nationality', ARRAY['Ivorian'], 'Clubs', ARRAY['Brighton', 'Union Saint-Gilloise'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Winger'],
 'Record / Trophy', ARRAY['AFCON winner with Ivory Coast 2024 — scored in the tournament'],
 'Career Moment', ARRAY['Signed permanently by Brighton after an outstanding loan at Union SG'],
 'Notable Fact', ARRAY['One of the fastest wingers in the PL — direct and unpredictable'],
 72.00, TRUE),

('Evan Ferguson',
 '2004-10-19', 'Libra', 'Footballer', 'Premier League', 'Irish', 'Male',
 'Nationality', ARRAY['Irish'], 'Clubs', ARRAY['Brighton', 'Bohemian FC'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Forward'],
 'Record / Trophy', ARRAY['Scored 8 PL goals before turning 19 — youngest Brighton player to score a hat-trick'],
 'Career Moment', ARRAY['Scored hat-trick vs Newcastle aged 18 in 2022 — announced himself to the world'],
 'Notable Fact', ARRAY['Republic of Ireland international — one of the most hyped teenagers in European football'],
 74.00, TRUE),

('Danny Welbeck',
 '1990-11-26', 'Sagittarius', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English', 'Ghanaian'], 'Clubs', ARRAY['Brighton', 'Watford', 'Arsenal', 'Manchester United'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Forward'],
 'Record / Trophy', ARRAY['Premier League winner with Manchester United 2012–13'],
 'Career Moment', ARRAY['Scored a winner for Arsenal vs Man Utd in 2014 — emotional celebration vs his former club'],
 'Notable Fact', ARRAY['Career ravaged by injury yet still playing PL football in his mid-30s'],
 72.00, TRUE),

-- ─── WEST HAM UNITED ──────────────────────────────────────────────────────────

('Alphonse Areola',
 '1993-02-27', 'Pisces', 'Footballer', 'Premier League', 'French', 'Male',
 'Nationality', ARRAY['French', 'Filipino'], 'Clubs', ARRAY['West Ham United', 'Paris Saint-Germain', 'Real Madrid'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['Champions League winner with Real Madrid in 2018 as third-choice keeper'],
 'Career Moment', ARRAY['Signed permanently by West Ham for £8m — reliable PL starter'],
 'Notable Fact', ARRAY['Has Filipino heritage through his mother — holds dual nationality'],
 72.00, TRUE),

('Jarrod Bowen',
 '1996-12-20', 'Sagittarius', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['West Ham United', 'Hull City'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Winger', 'Forward'],
 'Record / Trophy', ARRAY['Europa Conference League winner with West Ham in 2023'],
 'Career Moment', ARRAY['Scored 12 PL goals and 9 assists in 2021–22 — West Ham''s best modern season'],
 'Notable Fact', ARRAY['Signed for £18m from Hull in 2020 — now worth 10x that in the market'],
 78.00, TRUE),

('Mohammed Kudus',
 '2000-08-02', 'Leo', 'Footballer', 'Premier League', 'Ghanaian', 'Male',
 'Nationality', ARRAY['Ghanaian'], 'Clubs', ARRAY['West Ham United', 'Ajax', 'FC Nordsjælland'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Attacking Midfielder', 'Winger'],
 'Record / Trophy', ARRAY['Signed by West Ham for £38m from Ajax in 2023 — one of Africa''s best talents'],
 'Career Moment', ARRAY['Scored two goals on his first start for West Ham vs Sheffield United'],
 'Notable Fact', ARRAY['Ghana international — versatile and dangerous in multiple positions in attack'],
 76.00, TRUE),

('James Ward-Prowse',
 '1994-11-01', 'Scorpio', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['West Ham United', 'Southampton'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Central Midfielder'],
 'Record / Trophy', ARRAY['The Premier League''s best direct free kick taker of his generation'],
 'Career Moment', ARRAY['Scored from a free kick for Southampton vs Manchester City — one of many stunning set pieces'],
 'Notable Fact', ARRAY['Holds the record for most PL free kick goals since the competition began in 1992'],
 77.00, TRUE),

('Lucas Paqueta',
 '1997-08-27', 'Virgo', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 'Nationality', ARRAY['Brazilian'], 'Clubs', ARRAY['West Ham United', 'Lyon', 'AC Milan', 'Flamengo'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Attacking Midfielder'],
 'Record / Trophy', ARRAY['Copa America winner with Brazil 2019 — creative mainstay for the national side'],
 'Career Moment', ARRAY['Subject of an FA betting investigation — awaiting outcome while still playing'],
 'Notable Fact', ARRAY['Signed by West Ham for £51m in 2022 — elegant Brazilian No.10 style'],
 77.00, TRUE),

('Edson Alvarez',
 '1997-10-24', 'Scorpio', 'Footballer', 'Premier League', 'Mexican', 'Male',
 'Nationality', ARRAY['Mexican'], 'Clubs', ARRAY['West Ham United', 'Ajax', 'Club America'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Defensive Midfielder', 'Centre Back'],
 'Record / Trophy', ARRAY['Signed by West Ham for £35m from Ajax in 2023 — Mexico''s key defensive midfielder'],
 'Career Moment', ARRAY['Part of the Ajax squad in their 2018–19 Champions League semi-final run'],
 'Notable Fact', ARRAY['Mexico captain — can also play as an emergency centre-back'],
 74.00, TRUE),

('Crysencio Summerville',
 '2001-10-04', 'Libra', 'Footballer', 'Premier League', 'Dutch', 'Male',
 'Nationality', ARRAY['Dutch', 'Surinamese'], 'Clubs', ARRAY['West Ham United', 'Leeds United', 'Feyenoord'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Winger'],
 'Record / Trophy', ARRAY['Championship Player of the Season 2023–24 with Leeds — 20 goals'],
 'Career Moment', ARRAY['Signed by West Ham for £25m in 2024 — among the best from the Championship'],
 'Notable Fact', ARRAY['Netherlands international — explosive pace and direct dribbling style'],
 74.00, TRUE),

-- ─── BRENTFORD ────────────────────────────────────────────────────────────────

('Mark Flekken',
 '1993-06-13', 'Gemini', 'Footballer', 'Premier League', 'German', 'Male',
 'Nationality', ARRAY['German', 'Dutch'], 'Clubs', ARRAY['Brentford', 'Freiburg', 'Duisburg'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['Germany''s backup goalkeeper — solid and reliable at Brentford'],
 'Career Moment', ARRAY['Signed from Freiburg for £8.5m in 2023 — consistent in the PL'],
 'Notable Fact', ARRAY['Holds both German and Dutch passports — chose to play for Germany internationally'],
 70.00, TRUE),

('Nathan Collins',
 '2001-04-30', 'Taurus', 'Footballer', 'Premier League', 'Irish', 'Male',
 'Nationality', ARRAY['Irish'], 'Clubs', ARRAY['Brentford', 'Wolves', 'Burnley', 'Stoke City'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['Republic of Ireland international — signed by Brentford for £23m in 2023'],
 'Career Moment', ARRAY['Red-carded for a kung-fu challenge on Jack Grealish vs Man City at Wolves'],
 'Notable Fact', ARRAY['One of the most physically dominant young defenders in the PL'],
 72.00, TRUE),

('Bryan Mbeumo',
 '1999-08-07', 'Leo', 'Footballer', 'Premier League', 'Cameroonian', 'Male',
 'Nationality', ARRAY['Cameroonian', 'French'], 'Clubs', ARRAY['Brentford', 'Troyes'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Winger', 'Forward'],
 'Record / Trophy', ARRAY['20+ PL goals in 2023–24 — Brentford''s standout performer'],
 'Career Moment', ARRAY['Took on the goalscoring burden after Ivan Toney left and delivered emphatically'],
 'Notable Fact', ARRAY['Chose to represent Cameroon over France — AFCON regular for the Lions'],
 78.00, TRUE),

('Yoane Wissa',
 '1996-09-03', 'Virgo', 'Footballer', 'Premier League', 'Congolese', 'Male',
 'Nationality', ARRAY['Congolese', 'French'], 'Clubs', ARRAY['Brentford', 'Lorient', 'Angers'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Forward', 'Left Winger'],
 'Record / Trophy', ARRAY['DR Congo international — key part of Brentford''s PL survival campaigns'],
 'Career Moment', ARRAY['Scored vital goals to keep Brentford in the PL in back-to-back seasons'],
 'Notable Fact', ARRAY['Clinical finisher who thrives in Brentford''s direct attacking system'],
 73.00, TRUE),

('Christian Norgaard',
 '1994-03-10', 'Pisces', 'Footballer', 'Premier League', 'Danish', 'Male',
 'Nationality', ARRAY['Danish'], 'Clubs', ARRAY['Brentford', 'Fiorentina', 'Brondby'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Defensive Midfielder'],
 'Record / Trophy', ARRAY['Denmark international — one of Brentford''s most important players since promotion'],
 'Career Moment', ARRAY['Captained Brentford in the Championship and helped them reach the PL for the first time'],
 'Notable Fact', ARRAY['Signed for just £2m in 2019 — among the best free transfers in recent PL history'],
 72.00, TRUE),

('Mikkel Damsgaard',
 '2000-07-03', 'Cancer', 'Footballer', 'Premier League', 'Danish', 'Male',
 'Nationality', ARRAY['Danish'], 'Clubs', ARRAY['Brentford', 'Sampdoria', 'Nordsjaelland'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Attacking Midfielder', 'Winger'],
 'Record / Trophy', ARRAY['Scored a stunning free kick vs England at Euro 2020 semi-final'],
 'Career Moment', ARRAY['Became Denmark''s key creative player after Christian Eriksen''s cardiac arrest'],
 'Notable Fact', ARRAY['Signed by Brentford for £14m — consistent and creative in the PL'],
 74.00, TRUE),

-- ─── CRYSTAL PALACE ───────────────────────────────────────────────────────────

('Dean Henderson',
 '1997-03-12', 'Pisces', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Crystal Palace', 'Nottingham Forest', 'Manchester United'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['England international — signed by Crystal Palace for £5m in 2023'],
 'Career Moment', ARRAY['Left Man Utd on loan to Nottingham Forest and Crystal Palace — never went back'],
 'Notable Fact', ARRAY['Reached the World Cup squad with England in 2022 — competing with Pickford for the shirt'],
 72.00, TRUE),

('Marc Guehi',
 '2000-07-13', 'Cancer', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English', 'Congolese'], 'Clubs', ARRAY['Crystal Palace', 'Chelsea', 'Swansea City'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['Euro 2024 finalist with England — one of England''s best defenders'],
 'Career Moment', ARRAY['Signed from Chelsea for £18m in 2021 — became one of the PL''s best CBs'],
 'Notable Fact', ARRAY['Chelsea academy product — Palace got exceptional value on this deal'],
 80.00, TRUE),

('Joachim Andersen',
 '1996-05-31', 'Gemini', 'Footballer', 'Premier League', 'Danish', 'Male',
 'Nationality', ARRAY['Danish'], 'Clubs', ARRAY['Crystal Palace', 'Lyon', 'Sampdoria', 'Fiorentina'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['Denmark international and Crystal Palace''s most consistent defender'],
 'Career Moment', ARRAY['Signed permanently by Palace for £14m in 2022 after a successful loan'],
 'Notable Fact', ARRAY['Calm and commanding — excellent on the ball for a physical centre back'],
 74.00, TRUE),

('Eberechi Eze',
 '1998-06-29', 'Cancer', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English', 'Nigerian'], 'Clubs', ARRAY['Crystal Palace', 'Queens Park Rangers'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Attacking Midfielder'],
 'Record / Trophy', ARRAY['Euro 2024 finalist with England — one of the most creative PL midfielders'],
 'Career Moment', ARRAY['Scored a stunning solo goal vs Man Utd 2024 — one of the goals of the season'],
 'Notable Fact', ARRAY['Rejected multiple big clubs to stay at Palace — signed a long-term deal in 2024'],
 82.00, TRUE),

('Jean-Philippe Mateta',
 '1997-06-29', 'Cancer', 'Footballer', 'Premier League', 'French', 'Male',
 'Nationality', ARRAY['French', 'Ivorian'], 'Clubs', ARRAY['Crystal Palace', 'Mainz', 'Lyon'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Forward'],
 'Record / Trophy', ARRAY['Scored 16 Premier League goals in 2023–24 — Palace''s joint top scorer'],
 'Career Moment', ARRAY['Arrived on loan from Mainz struggling — transformed into a PL goalscorer'],
 'Notable Fact', ARRAY['One of football''s best comeback stories — written off before finding his feet at Palace'],
 75.00, TRUE),

('Daniel Munoz',
 '1996-11-29', 'Sagittarius', 'Footballer', 'Premier League', 'Colombian', 'Male',
 'Nationality', ARRAY['Colombian'], 'Clubs', ARRAY['Crystal Palace', 'Genk', 'Atletico Nacional'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Back'],
 'Record / Trophy', ARRAY['Colombia international — Copa America 2024 runner-up'],
 'Career Moment', ARRAY['Signed by Crystal Palace for £12m from Genk in 2024 — excellent first season'],
 'Notable Fact', ARRAY['Attacking full back — a surprise package in Palace''s squad from his first game'],
 72.00, TRUE),

-- ─── WOLVERHAMPTON WANDERERS ──────────────────────────────────────────────────

('Jose Sa',
 '1993-01-17', 'Capricorn', 'Footballer', 'Premier League', 'Portuguese', 'Male',
 'Nationality', ARRAY['Portuguese'], 'Clubs', ARRAY['Wolverhampton Wanderers', 'Olympiakos', 'Porto'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['Portugal international — one of the most consistent keepers in the PL'],
 'Career Moment', ARRAY['Signed for £6.5m from Olympiakos in 2021 — one of the best goalkeeper signings of that era'],
 'Notable Fact', ARRAY['Kept Wolves in the PL almost single-handedly in multiple seasons through outstanding form'],
 74.00, TRUE),

('Max Kilman',
 '1997-05-23', 'Gemini', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Wolverhampton Wanderers', 'Maidenhead United'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['England international — a remarkable rise from non-league football'],
 'Career Moment', ARRAY['Signed from Maidenhead United — went from non-league to England senior team'],
 'Notable Fact', ARRAY['Voted Wolves'' Player of the Season multiple times — a model of consistency'],
 75.00, TRUE),

('Nelson Semedo',
 '1993-11-16', 'Scorpio', 'Footballer', 'Premier League', 'Portuguese', 'Male',
 'Nationality', ARRAY['Portuguese'], 'Clubs', ARRAY['Wolverhampton Wanderers', 'Barcelona', 'Benfica'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Back'],
 'Record / Trophy', ARRAY['Portugal international — two La Liga titles with Barcelona'],
 'Career Moment', ARRAY['Signed by Wolves for £27m from Barcelona in 2020 — one of the club''s biggest signings'],
 'Notable Fact', ARRAY['One of the most attack-minded right backs in the PL — pace and crossing a strength'],
 73.00, TRUE),

('Rayan Ait-Nouri',
 '2001-06-06', 'Gemini', 'Footballer', 'Premier League', 'French', 'Male',
 'Nationality', ARRAY['French', 'Algerian'], 'Clubs', ARRAY['Wolverhampton Wanderers', 'Angers'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Back'],
 'Record / Trophy', ARRAY['Algeria international — one of the best attacking left backs in the PL'],
 'Career Moment', ARRAY['Chose to represent Algeria over France — committed to them in 2022'],
 'Notable Fact', ARRAY['Signed permanently by Wolves for £10m — consistently one of their best players'],
 74.00, TRUE),

('Matheus Cunha',
 '1999-05-27', 'Gemini', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 'Nationality', ARRAY['Brazilian'], 'Clubs', ARRAY['Wolverhampton Wanderers', 'Atletico Madrid', 'Hertha Berlin'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Forward', 'Attacking Midfielder'],
 'Record / Trophy', ARRAY['Wolves'' standout player — double-digit PL goals in 2023–24'],
 'Career Moment', ARRAY['Signed permanently for £43m in 2023 after an outstanding loan spell'],
 'Notable Fact', ARRAY['Brazil international who became one of the PL''s most dangerous attackers'],
 79.00, TRUE),

('Hwang Hee-chan',
 '1996-01-26', 'Aquarius', 'Footballer', 'Premier League', 'South Korean', 'Male',
 'Nationality', ARRAY['South Korean'], 'Clubs', ARRAY['Wolverhampton Wanderers', 'RB Leipzig', 'Hamburg', 'RB Salzburg'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Forward', 'Winger'],
 'Record / Trophy', ARRAY['10 Premier League goals in 2022–23 — Wolves'' top scorer'],
 'Career Moment', ARRAY['Scored the winner vs Portugal at 2022 World Cup — South Korea''s dramatic comeback'],
 'Notable Fact', ARRAY['Part of South Korea''s military exemption squad at the 2018 Asian Games'],
 74.00, TRUE),

-- ─── FULHAM ───────────────────────────────────────────────────────────────────

('Bernd Leno',
 '1992-03-04', 'Pisces', 'Footballer', 'Premier League', 'German', 'Male',
 'Nationality', ARRAY['German'], 'Clubs', ARRAY['Fulham', 'Arsenal', 'Bayer Leverkusen'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['Germany international — reliable PL keeper with over 200 PL appearances'],
 'Career Moment', ARRAY['Left Arsenal to join Fulham in 2022 — found his best form away from the pressure'],
 'Notable Fact', ARRAY['Was Arsenal''s No.1 before losing his place to Aaron Ramsdale — rebuilt at Fulham'],
 73.00, TRUE),

('Antonee Robinson',
 '1997-08-08', 'Leo', 'Footballer', 'Premier League', 'American', 'Male',
 'Nationality', ARRAY['American'], 'Clubs', ARRAY['Fulham', 'Wigan Athletic', 'Everton'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Back'],
 'Record / Trophy', ARRAY['USA international — one of the best American defenders ever to play in the PL'],
 'Career Moment', ARRAY['Almost joined AC Milan in 2020 — deal collapsed due to a failed medical'],
 'Notable Fact', ARRAY['Captain of the USMNT — one of the first Americans to establish himself as a PL regular'],
 74.00, TRUE),

('Alex Iwobi',
 '1996-05-03', 'Taurus', 'Footballer', 'Premier League', 'Nigerian', 'Male',
 'Nationality', ARRAY['Nigerian'], 'Clubs', ARRAY['Fulham', 'Everton', 'Arsenal'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Attacking Midfielder', 'Winger'],
 'Record / Trophy', ARRAY['Nigeria international — one of Fulham''s most creative players'],
 'Career Moment', ARRAY['Reinvented himself as a central midfielder at Fulham after years as a winger'],
 'Notable Fact', ARRAY['Nephew of Nigerian legend Jay-Jay Okocha — came through Arsenal''s academy'],
 74.00, TRUE),

('Raul Jimenez',
 '1991-05-05', 'Taurus', 'Footballer', 'Premier League', 'Mexican', 'Male',
 'Nationality', ARRAY['Mexican'], 'Clubs', ARRAY['Fulham', 'Wolves', 'Atletico Madrid', 'Benfica'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Forward'],
 'Record / Trophy', ARRAY['Mexico''s all-time top scorer — a national hero'],
 'Career Moment', ARRAY['Suffered a fractured skull vs Arsenal 2020 — made a remarkable full recovery'],
 'Notable Fact', ARRAY['Wore a protective head guard for months after surgery — later discarded it'],
 76.00, TRUE),

('Rodrigo Muniz',
 '2001-05-17', 'Taurus', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 'Nationality', ARRAY['Brazilian'], 'Clubs', ARRAY['Fulham', 'Middlesbrough', 'Flamengo'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Forward'],
 'Record / Trophy', ARRAY['13 Premier League goals in 2023–24 — Fulham''s top scorer'],
 'Career Moment', ARRAY['Signed from Flamengo — established himself as a PL-quality striker at Fulham'],
 'Notable Fact', ARRAY['Brazil Under-23 international — powerful and clinical in front of goal'],
 72.00, TRUE),

('Harrison Reed',
 '1995-01-27', 'Aquarius', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Fulham', 'Southampton', 'Blackburn Rovers'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Defensive Midfielder'],
 'Record / Trophy', ARRAY['Fulham''s engine room — key to their top-flight stability since promotion'],
 'Career Moment', ARRAY['Signed from Southampton for £10m in 2021 — became a PL regular in his 30s'],
 'Notable Fact', ARRAY['A classic "water-carrier" midfielder — protects the defence and recycles possession'],
 70.00, TRUE),

-- ─── EVERTON ──────────────────────────────────────────────────────────────────

('Jordan Pickford',
 '1994-03-07', 'Pisces', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Everton', 'Sunderland', 'Bradford City'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['England''s first-choice keeper — Euro 2020 finalist and 2022 World Cup starter'],
 'Career Moment', ARRAY['Saved Colombia''s penalty in the 2018 World Cup shootout — England''s most famous save in years'],
 'Notable Fact', ARRAY['Saved penalties at both Euro 2020 and 2022 World Cup — England''s Mr Reliable'],
 82.00, TRUE),

('Jarrad Branthwaite',
 '2002-06-27', 'Cancer', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Everton', 'Carlisle United'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['Euro 2024 finalist with England — called up after an outstanding PL season'],
 'Career Moment', ARRAY['Man Utd reportedly bid £70m+ for him in 2024 — Everton rejected it'],
 'Notable Fact', ARRAY['Came through Carlisle United before Everton signed him for just £1.5m'],
 77.00, TRUE),

('James Tarkowski',
 '1992-11-19', 'Scorpio', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Everton', 'Burnley', 'Brentford'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['Everton''s first-choice centre back — a calming presence in a turbulent era'],
 'Career Moment', ARRAY['Joined Everton on a free in 2022 — one of the club''s best signings of recent years'],
 'Notable Fact', ARRAY['Played championship football with Burnley and adapted seamlessly to top-flight level'],
 72.00, TRUE),

('Dwight McNeil',
 '2000-11-22', 'Sagittarius', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Everton', 'Burnley'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Winger', 'Attacking Midfielder'],
 'Record / Trophy', ARRAY['Everton''s most reliable attacker since his 2022 signing from Burnley'],
 'Career Moment', ARRAY['Signed for £20m — one of the few positive stories in Everton''s difficult recent era'],
 'Notable Fact', ARRAY['Nephew of former Man Utd midfielder Nicky Butt''s team-mate Phil Neville (unrelated — but often confused)'],
 72.00, TRUE),

('Dominic Calvert-Lewin',
 '1997-03-16', 'Pisces', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Everton', 'Sheffield United', 'Stalybridge Celtic'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Forward'],
 'Record / Trophy', ARRAY['16 Premier League goals in 2020–21 — Everton''s best season in years'],
 'Career Moment', ARRAY['England international who scored on his senior debut vs Republic of Ireland'],
 'Notable Fact', ARRAY['Known as much for his high fashion modelling as his football — a style icon'],
 74.00, TRUE),

-- ─── NOTTINGHAM FOREST ────────────────────────────────────────────────────────

('Matz Sels',
 '1992-02-26', 'Pisces', 'Footballer', 'Premier League', 'Belgian', 'Male',
 'Nationality', ARRAY['Belgian'], 'Clubs', ARRAY['Nottingham Forest', 'Strasbourg', 'Newcastle United'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['Belgium international — key to Forest''s top-half PL finishes'],
 'Career Moment', ARRAY['Signed from Strasbourg for £3m in 2024 — one of the best value GK signings'],
 'Notable Fact', ARRAY['Played under Bosz and various coaches — a journeyman who found a home at Forest'],
 70.00, TRUE),

('Nikola Milenkovic',
 '1997-10-12', 'Libra', 'Footballer', 'Premier League', 'Serbian', 'Male',
 'Nationality', ARRAY['Serbian'], 'Clubs', ARRAY['Nottingham Forest', 'Fiorentina', 'Partizan'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['Serbia international — signed by Forest for £11m in 2024'],
 'Career Moment', ARRAY['Spent 7 years at Fiorentina before making his PL debut at 26'],
 'Notable Fact', ARRAY['Powerful and dominant in the air — one of Serie A''s best CBs before moving to the PL'],
 72.00, TRUE),

('Morgan Gibbs-White',
 '2000-01-27', 'Aquarius', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Nottingham Forest', 'Wolves', 'Sheffield United'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Attacking Midfielder'],
 'Record / Trophy', ARRAY['Signed by Forest for £42m from Wolves in 2022 — club record'],
 'Career Moment', ARRAY['Transformed under Steve Cooper — one of the PL''s best playmakers in 2023–24'],
 'Notable Fact', ARRAY['England Under-21 international — shone when lent the creative freedom at Forest'],
 76.00, TRUE),

('Anthony Elanga',
 '2002-04-27', 'Taurus', 'Footballer', 'Premier League', 'Swedish', 'Male',
 'Nationality', ARRAY['Swedish', 'Cameroonian'], 'Clubs', ARRAY['Nottingham Forest', 'Manchester United'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Winger', 'Left Winger'],
 'Record / Trophy', ARRAY['Signed by Forest for £15m from Man Utd in 2023 — a consistent threat'],
 'Career Moment', ARRAY['One of the fastest players in the PL — recorded among the top sprint speeds'],
 'Notable Fact', ARRAY['Son of former Cameroon international Joseph-Andre Elanga'],
 73.00, TRUE),

('Callum Hudson-Odoi',
 '2001-04-05', 'Aries', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English', 'Ghanaian'], 'Clubs', ARRAY['Nottingham Forest', 'Chelsea', 'Bayer Leverkusen'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Winger', 'Forward'],
 'Record / Trophy', ARRAY['Reinvented himself under Nuno at Nottingham Forest in 2023–24'],
 'Career Moment', ARRAY['Left Chelsea permanently in 2024 — finally found consistent form away from Stamford Bridge'],
 'Notable Fact', ARRAY['Was one of the most hyped English teenagers in 2018 — Bayern Munich tried to sign him'],
 73.00, TRUE),

('Chris Wood',
 '1991-12-07', 'Sagittarius', 'Footballer', 'Premier League', 'New Zealander', 'Male',
 'Nationality', ARRAY['New Zealander'], 'Clubs', ARRAY['Nottingham Forest', 'Newcastle United', 'Burnley', 'Leeds United'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Forward'],
 'Record / Trophy', ARRAY['New Zealand''s all-time top scorer — scored 14 PL goals for Forest in 2023–24'],
 'Career Moment', ARRAY['Signed by Newcastle for £25m in January 2022 — an early signal of their ambition'],
 'Notable Fact', ARRAY['Played PL football for four different clubs including against each other in the same season'],
 73.00, TRUE),

-- ─── BOURNEMOUTH ──────────────────────────────────────────────────────────────

('Neto',
 '1989-07-19', 'Cancer', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 'Nationality', ARRAY['Brazilian'], 'Clubs', ARRAY['Bournemouth', 'Barcelona', 'Valencia', 'Juventus'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['Champions League experience with Barcelona — now a reliable PL keeper'],
 'Career Moment', ARRAY['Signed by Bournemouth from Barcelona — rebuilding career in the PL'],
 'Notable Fact', ARRAY['Full name Pedro Neto — not to be confused with the Chelsea winger Pedro Neto'],
 70.00, TRUE),

('Marcos Senesi',
 '1997-05-10', 'Taurus', 'Footballer', 'Premier League', 'Argentine', 'Male',
 'Nationality', ARRAY['Argentine'], 'Clubs', ARRAY['Bournemouth', 'Feyenoord', 'San Lorenzo'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['Argentina squad member — signed by Bournemouth for £15m from Feyenoord'],
 'Career Moment', ARRAY['Won the Eredivisie with Feyenoord before stepping up to the Premier League'],
 'Notable Fact', ARRAY['One of Bournemouth''s most composed defenders in their top-flight journey'],
 71.00, TRUE),

('Ilya Zabarnyi',
 '2002-09-01', 'Virgo', 'Footballer', 'Premier League', 'Ukrainian', 'Male',
 'Nationality', ARRAY['Ukrainian'], 'Clubs', ARRAY['Bournemouth', 'Dynamo Kyiv'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Back'],
 'Record / Trophy', ARRAY['Ukraine international — signed by Bournemouth for £24m in January 2023'],
 'Career Moment', ARRAY['Left Ukraine during the war in 2022 — joined Bournemouth and settled quickly'],
 'Notable Fact', ARRAY['One of the youngest players to represent Ukraine at senior international level'],
 72.00, TRUE),

('Milos Kerkez',
 '2003-11-05', 'Scorpio', 'Footballer', 'Premier League', 'Hungarian', 'Male',
 'Nationality', ARRAY['Hungarian'], 'Clubs', ARRAY['Bournemouth', 'AZ Alkmaar', 'AC Milan'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Back'],
 'Record / Trophy', ARRAY['Hungary international — one of the most sought-after young left backs in Europe'],
 'Career Moment', ARRAY['Signed from AZ for £12m — immediately established himself as one of the PL''s best left backs'],
 'Notable Fact', ARRAY['Was linked with Liverpool and multiple top clubs in 2024 — chose to stay at Bournemouth'],
 74.00, TRUE),

('Antoine Semenyo',
 '2000-01-07', 'Capricorn', 'Footballer', 'Premier League', 'Ghanaian', 'Male',
 'Nationality', ARRAY['Ghanaian', 'British'], 'Clubs', ARRAY['Bournemouth', 'Bristol City'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Winger'],
 'Record / Trophy', ARRAY['Ghana international — Bournemouth''s most direct wide threat'],
 'Career Moment', ARRAY['Signed from Bristol City for £15m in 2023 — scored on his debut vs Aston Villa'],
 'Notable Fact', ARRAY['Rapid and direct — one of the most electrifying wide players outside the top six'],
 72.00, TRUE),

('Evanilson',
 '1999-04-09', 'Aries', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 'Nationality', ARRAY['Brazilian'], 'Clubs', ARRAY['Bournemouth', 'Porto', 'Fluminense'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Centre Forward'],
 'Record / Trophy', ARRAY['Signed by Bournemouth for £29m from Porto in 2024'],
 'Career Moment', ARRAY['Scored 26 goals for Porto in 2023–24 — attracted Bournemouth''s attention'],
 'Notable Fact', ARRAY['Brazil Under-23 international — powerful striker comfortable in tight spaces'],
 72.00, TRUE),

('Dango Ouattara',
 '2002-02-11', 'Aquarius', 'Footballer', 'Premier League', 'Burkinabe', 'Male',
 'Nationality', ARRAY['Burkinabe'], 'Clubs', ARRAY['Bournemouth', 'Lorient'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Right Winger'],
 'Record / Trophy', ARRAY['Signed by Bournemouth for £20m from Lorient in 2023 — a raw but dangerous winger'],
 'Career Moment', ARRAY['Scored on his PL debut — one of the fastest players in the league'],
 'Notable Fact', ARRAY['Burkina Faso international — one of the very few Burkinabe players in the PL'],
 71.00, TRUE),

('Lewis Cook',
 '1997-02-03', 'Aquarius', 'Footballer', 'Premier League', 'English', 'Male',
 'Nationality', ARRAY['English'], 'Clubs', ARRAY['Bournemouth', 'Leeds United'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Defensive Midfielder', 'Central Midfielder'],
 'Record / Trophy', ARRAY['England Under-20 World Cup winner 2017 — as captain'],
 'Career Moment', ARRAY['Suffered ACL injury in 2019 — remarkable recovery to become Bournemouth''s midfield anchor'],
 'Notable Fact', ARRAY['Captained England Under-20s to World Cup glory — consistent PL performer for Bournemouth'],
 72.00, TRUE),

-- ─── LEICESTER CITY ───────────────────────────────────────────────────────────

('Mads Hermansen',
 '1999-06-28', 'Cancer', 'Footballer', 'Premier League', 'Danish', 'Male',
 'Nationality', ARRAY['Danish'], 'Clubs', ARRAY['Leicester City', 'Brondby'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Goalkeeper'],
 'Record / Trophy', ARRAY['Denmark international — key in Leicester''s Championship-winning 2023–24 season'],
 'Career Moment', ARRAY['Signed from Brondby for £4.5m in 2023 — exceeded expectations immediately'],
 'Notable Fact', ARRAY['The most expensive Danish goalkeeper sold at that point — a bargain in hindsight'],
 70.00, TRUE),

('Stephy Mavididi',
 '1998-05-30', 'Gemini', 'Footballer', 'Premier League', 'French', 'Male',
 'Nationality', ARRAY['French', 'Congolese'], 'Clubs', ARRAY['Leicester City', 'Montpellier', 'Juventus'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Winger'],
 'Record / Trophy', ARRAY['Key winger in Leicester''s 2023–24 Championship winning campaign'],
 'Career Moment', ARRAY['Joined Leicester on a free — one of the standout wide players in the Championship'],
 'Notable Fact', ARRAY['Born in England, raised in France — chose France for international football'],
 70.00, TRUE),

('Viktor Kristiansen',
 '2002-08-10', 'Leo', 'Footballer', 'Premier League', 'Danish', 'Male',
 'Nationality', ARRAY['Danish'], 'Clubs', ARRAY['Leicester City', 'Copenhagen'],
 'Career Status', ARRAY['Active'], 'Position(s)', ARRAY['Left Back'],
 'Record / Trophy', ARRAY['Denmark international — signed by Leicester for £17m from Copenhagen'],
 'Career Moment', ARRAY['Loaned back to Copenhagen then returned to Leicester as a first-team regular'],
 'Notable Fact', ARRAY['One of the youngest regular left backs at PL level'],
 69.00, TRUE);
