-- Seed: Premier League Footballers
-- 66 players across eras with full attribute and known_for data
-- Column semantics: see data_products/docs/celebrity_column_semantics.md

INSERT INTO ofta_prod.ofta_person (
    full_name, date_of_birth, star_sign,
    primary_category, secondary_category,
    nationality, gender,
    attr_1, attr_2, attr_3, attr_4,
    known_for_1, known_for_2, known_for_3,
    popularity_score, is_active
) VALUES

-- ─── ARSENAL LEGENDS ──────────────────────────────────────────────────────────

('Thierry Henry',
 '1977-08-17', 'Leo', 'Footballer', 'Premier League', 'French', 'Male',
 ARRAY['French'],
 ARRAY['Arsenal', 'Barcelona', 'New York Red Bulls'],
 ARRAY['Retired'], ARRAY['Forward'],
 'Arsenal all-time top scorer with 228 goals',
 'Part of Arsenal''s unbeaten Invincibles season 2003–04',
 '1998 World Cup and 2000 Euros winner with France',
 96.00, FALSE),

('Patrick Vieira',
 '1975-06-23', 'Cancer', 'Footballer', 'Premier League', 'French', 'Male',
 ARRAY['French', 'Senegalese'],
 ARRAY['Arsenal', 'Juventus', 'Inter Milan', 'Manchester City'],
 ARRAY['Retired'], ARRAY['Midfielder'],
 'Arsenal captain during the unbeaten Invincibles season 2003–04',
 '1998 World Cup and 2000 Euros winner with France',
 'Three Premier League titles — left Arsenal in acrimonious 2005 exit',
 89.00, FALSE),

('Dennis Bergkamp',
 '1969-05-10', 'Taurus', 'Footballer', 'Premier League', 'Dutch', 'Male',
 ARRAY['Dutch'],
 ARRAY['Arsenal', 'Inter Milan', 'Ajax'],
 ARRAY['Retired'], ARRAY['Forward', 'Attacking Midfielder'],
 'Iconic goal vs Argentina at 1998 World Cup — voted FIFA goal of the year',
 'Refused to fly — nicknamed The Non-Flying Dutchman',
 'Three Premier League titles and two FA Cups with Arsenal',
 88.00, FALSE),

('Tony Adams',
 '1966-10-10', 'Libra', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Arsenal'],
 ARRAY['Retired'], ARRAY['Centre Back'],
 'Arsenal captain for 19 years — one-club career spanning 1983 to 2002',
 'Four league titles across two eras: 1989, 1991, 1998, 2002',
 'Publicly overcame alcohol addiction — influential voice on mental health in football',
 84.00, FALSE),

('Ian Wright',
 '1963-11-03', 'Scorpio', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Arsenal', 'Crystal Palace', 'West Ham United', 'Nottingham Forest'],
 ARRAY['Retired'], ARRAY['Forward'],
 'Arsenal''s all-time top scorer before Henry — 185 goals in all competitions',
 'Celebrated breaking Cliff Bastin''s record by revealing a "179" shirt',
 'Crystal Palace cult hero before becoming an Arsenal icon',
 83.00, FALSE),

('Robert Pires',
 '1973-10-29', 'Scorpio', 'Footballer', 'Premier League', 'French', 'Male',
 ARRAY['French', 'Portuguese'],
 ARRAY['Arsenal', 'Villarreal', 'Aston Villa', 'Marseille'],
 ARRAY['Retired'], ARRAY['Left Winger', 'Attacking Midfielder'],
 'PFA Players'' Player of the Year 2002 — part of Arsenal''s Invincibles',
 '1998 World Cup and 2000 Euros winner with France',
 'Missed FA Cup final penalty in 2005 — passed it to Henry who had no shot',
 82.00, FALSE),

('Sol Campbell',
 '1974-09-18', 'Virgo', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English', 'Jamaican'],
 ARRAY['Arsenal', 'Tottenham Hotspur', 'Portsmouth', 'Notts County'],
 ARRAY['Retired'], ARRAY['Centre Back'],
 'Left Spurs on a free transfer to join Arsenal in 2001 — one of football''s most controversial moves',
 'Part of Arsenal''s unbeaten Invincibles 2003–04',
 'Won Premier League and FA Cup double with Arsenal in 2002',
 83.00, FALSE),

('Bukayo Saka',
 '2001-09-05', 'Virgo', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English', 'Nigerian'],
 ARRAY['Arsenal'],
 ARRAY['Active'], ARRAY['Right Winger', 'Midfielder'],
 'Arsenal''s most consistent performer — key in PL title challenges 2022–24',
 'Missed the decisive penalty in Euro 2020 final shootout vs Italy',
 'BBC Young Sports Personality of the Year 2020',
 88.00, TRUE),

('Martin Odegaard',
 '1998-12-17', 'Sagittarius', 'Footballer', 'Premier League', 'Norwegian', 'Male',
 ARRAY['Norwegian'],
 ARRAY['Arsenal', 'Real Madrid', 'Real Sociedad', 'Vitesse'],
 ARRAY['Active'], ARRAY['Attacking Midfielder'],
 'Arsenal captain — central to title challenges in 2022–23 and 2023–24',
 'Youngest player ever to appear for Real Madrid''s first team at the time of debut',
 'Norwegian captain — leads both club and country as a creative midfielder',
 86.00, TRUE),

('Declan Rice',
 '1999-01-14', 'Capricorn', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English', 'Irish'],
 ARRAY['Arsenal', 'West Ham United'],
 ARRAY['Active'], ARRAY['Defensive Midfielder'],
 '£105m transfer to Arsenal in 2023 — British transfer record at the time',
 'Led West Ham to 2023 UEFA Europa Conference League — their first European trophy',
 'Euro 2020 finalist with England',
 87.00, TRUE),

('Gabriel Martinelli',
 '2001-06-18', 'Gemini', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 ARRAY['Brazilian'],
 ARRAY['Arsenal', 'Ituano'],
 ARRAY['Active'], ARRAY['Left Winger', 'Forward'],
 'Signed by Arsenal for £6m in 2019 — one of the best-value signings in PL history',
 'Scored 15 Premier League goals in 2022–23 — his breakthrough season',
 'Brazil international — key part of Arsenal''s front three',
 82.00, TRUE),

('William Saliba',
 '2001-06-24', 'Cancer', 'Footballer', 'Premier League', 'French', 'Male',
 ARRAY['French', 'Cameroonian'],
 ARRAY['Arsenal', 'Saint-Etienne', 'Nice', 'Marseille'],
 ARRAY['Active'], ARRAY['Centre Back'],
 'PL Young Player of the Season 2022–23',
 'Bought by Arsenal for £27m in 2019 then loaned three times before breaking through',
 'Transformed Arsenal''s defence — considered one of Europe''s best young defenders',
 82.00, TRUE),

('Cesc Fabregas',
 '1987-05-04', 'Taurus', 'Footballer', 'Premier League', 'Spanish', 'Male',
 ARRAY['Spanish'],
 ARRAY['Arsenal', 'Chelsea', 'Barcelona', 'Monaco', 'Como'],
 ARRAY['Retired'], ARRAY['Midfielder', 'Attacking Midfielder'],
 'Arsenal''s youngest ever scorer at 16 — debuted in 2003',
 '2010 World Cup and 2008/2012 Euros winner with Spain',
 'Premier League winner with Chelsea in 2015 and 2017',
 86.00, FALSE),

-- ─── MANCHESTER UNITED LEGENDS ────────────────────────────────────────────────

('Eric Cantona',
 '1966-05-24', 'Gemini', 'Footballer', 'Premier League', 'French', 'Male',
 ARRAY['French'],
 ARRAY['Manchester United', 'Leeds United', 'Marseille', 'Nimes'],
 ARRAY['Retired'], ARRAY['Forward'],
 'Infamous karate kick on a Crystal Palace fan at Selhurst Park in January 1995',
 'Four Premier League titles in five seasons with Manchester United',
 'Iconic collar-up persona — widely credited with transforming Man Utd',
 90.00, FALSE),

('Paul Scholes',
 '1974-11-16', 'Scorpio', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Manchester United'],
 ARRAY['Retired'], ARRAY['Midfielder'],
 '11 Premier League titles — one-club career at Manchester United',
 '1999 Champions League Treble winner with Man Utd',
 'Widely considered one of the greatest English midfielders ever',
 88.00, FALSE),

('Roy Keane',
 '1971-08-10', 'Leo', 'Footballer', 'Premier League', 'Irish', 'Male',
 ARRAY['Irish'],
 ARRAY['Manchester United', 'Nottingham Forest', 'Celtic'],
 ARRAY['Retired'], ARRAY['Midfielder'],
 'Inspirational vs Juventus in 1999 CL semi-final knowing he would miss the final',
 'Seven Premier League titles with Manchester United',
 'Left Man Utd in 2005 after explosive MUTV interview — one of football''s great fallouts',
 87.00, FALSE),

('Peter Schmeichel',
 '1963-11-18', 'Scorpio', 'Footballer', 'Premier League', 'Danish', 'Male',
 ARRAY['Danish'],
 ARRAY['Manchester United', 'Aston Villa', 'Manchester City', 'Sporting CP'],
 ARRAY['Retired'], ARRAY['Goalkeeper'],
 '1999 Champions League Treble winner — captain lifting the trophy in Barcelona',
 'Five Premier League titles with Manchester United',
 'Considered one of the greatest goalkeepers of all time',
 88.00, FALSE),

('Ryan Giggs',
 '1973-11-29', 'Sagittarius', 'Footballer', 'Premier League', 'Welsh', 'Male',
 ARRAY['Welsh'],
 ARRAY['Manchester United'],
 ARRAY['Retired'], ARRAY['Winger', 'Midfielder'],
 'Only player to appear in every one of the first 20 Premier League seasons (1992–2013)',
 '13 Premier League titles — the most of any player in history',
 'Mazy solo goal vs Arsenal in 1999 FA Cup semi-final — one of the greatest ever',
 91.00, FALSE),

('Wayne Rooney',
 '1985-10-24', 'Scorpio', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Manchester United', 'Everton', 'DC United', 'Derby County'],
 ARRAY['Retired'], ARRAY['Forward', 'Attacking Midfielder'],
 'Manchester United all-time top scorer with 253 goals across all competitions',
 'England''s all-time top scorer with 53 international goals',
 'Five Premier League titles and a Champions League with Man Utd',
 92.00, FALSE),

('Rio Ferdinand',
 '1978-11-07', 'Scorpio', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Manchester United', 'Leeds United', 'West Ham United', 'QPR'],
 ARRAY['Retired'], ARRAY['Centre Back'],
 'Six Premier League titles with Manchester United',
 '£29.1m transfer from Leeds to Man Utd in 2002 — a British record at the time',
 'Formed iconic defensive partnership with Nemanja Vidic',
 86.00, FALSE),

('Nemanja Vidic',
 '1981-10-21', 'Libra', 'Footballer', 'Premier League', 'Serbian', 'Male',
 ARRAY['Serbian'],
 ARRAY['Manchester United', 'Inter Milan', 'Spartak Moscow'],
 ARRAY['Retired'], ARRAY['Centre Back'],
 'Five Premier League titles with Manchester United',
 'PFA Players'' Player of the Year in 2009 and 2011',
 'Formed one of the PL''s greatest defensive partnerships alongside Rio Ferdinand',
 84.00, FALSE),

('Andy Cole',
 '1971-10-15', 'Libra', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Manchester United', 'Newcastle United', 'Blackburn Rovers', 'Fulham', 'Manchester City'],
 ARRAY['Retired'], ARRAY['Centre Forward'],
 'Scored 34 Premier League goals for Newcastle in 1993–94 — still a club record',
 '1999 Champions League Treble winner with Manchester United',
 'Five Premier League titles with Manchester United',
 80.00, FALSE),

('David Beckham',
 '1975-05-02', 'Taurus', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Manchester United', 'Real Madrid', 'LA Galaxy', 'AC Milan', 'Paris Saint-Germain'],
 ARRAY['Retired'], ARRAY['Right Midfielder', 'Right Back'],
 'Six Premier League titles with Manchester United',
 'Famous lob from halfway line vs Wimbledon on opening day 1996',
 'Became a global icon and co-founder of Inter Miami CF',
 91.00, FALSE),

('Paul Pogba',
 '1993-03-15', 'Pisces', 'Footballer', 'Premier League', 'French', 'Male',
 ARRAY['French', 'Guinean'],
 ARRAY['Manchester United', 'Juventus'],
 ARRAY['Retired'], ARRAY['Midfielder'],
 '£89m transfer back to Manchester United in 2016 — a world record at the time',
 '2018 FIFA World Cup winner with France',
 'Suspended for doping in 2023 — one of football''s most complicated careers',
 83.00, FALSE),

('Bruno Fernandes',
 '1994-09-08', 'Virgo', 'Footballer', 'Premier League', 'Portuguese', 'Male',
 ARRAY['Portuguese'],
 ARRAY['Manchester United', 'Sporting CP', 'Sampdoria', 'Udinese'],
 ARRAY['Active'], ARRAY['Attacking Midfielder'],
 'Transformed Manchester United from the moment of his January 2020 signing',
 'Most PL Player of the Month awards since joining Man Utd',
 'Most direct goal contributions (goals + assists) at Man Utd in the PL era',
 87.00, TRUE),

('Marcus Rashford',
 '1997-10-31', 'Scorpio', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Manchester United'],
 ARRAY['Active'], ARRAY['Forward', 'Left Winger'],
 'Scored 30 Premier League goals in 2022–23 — his best ever season',
 'Campaigned successfully for free school meals for vulnerable children during COVID-19',
 'Man Utd academy product — debuted aged 18 with two goals vs Midtjylland',
 86.00, TRUE),

('Carlos Tevez',
 '1984-02-05', 'Aquarius', 'Footballer', 'Premier League', 'Argentine', 'Male',
 ARRAY['Argentine'],
 ARRAY['Manchester United', 'Manchester City', 'West Ham United', 'Juventus'],
 ARRAY['Retired'], ARRAY['Forward', 'Attacking Midfielder'],
 '"Welcome to Manchester" billboard — iconic Man City ad trolling Man Utd',
 'Won Premier League with Manchester United (2008) and Manchester City (2012)',
 'World-record bid from Corinthians collapsed — one of football''s great transfer sagas',
 84.00, FALSE),

('Cristiano Ronaldo',
 '1985-02-05', 'Aquarius', 'Footballer', 'Premier League', 'Portuguese', 'Male',
 ARRAY['Portuguese'],
 ARRAY['Manchester United', 'Real Madrid', 'Juventus', 'Sporting CP', 'Al-Nassr'],
 ARRAY['Active'], ARRAY['Forward', 'Right Winger'],
 'Three Premier League titles with Manchester United — 2007, 2008, 2009',
 '£80m transfer to Real Madrid in 2009 — then a world-record fee',
 'International football''s all-time top scorer with over 130 goals for Portugal',
 98.00, TRUE),

-- ─── LIVERPOOL LEGENDS ────────────────────────────────────────────────────────

('Steven Gerrard',
 '1980-05-30', 'Gemini', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Liverpool', 'LA Galaxy'],
 ARRAY['Retired'], ARRAY['Midfielder'],
 '2005 Champions League comeback — scored in the legendary 3-3 vs AC Milan in Istanbul',
 'Liverpool captain for 12 years — never won the Premier League',
 'Slip vs Chelsea in 2014 that arguably cost Liverpool the title',
 93.00, FALSE),

('Jamie Carragher',
 '1978-01-28', 'Aquarius', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Liverpool'],
 ARRAY['Retired'], ARRAY['Centre Back', 'Right Back'],
 '2005 Champions League winner with Liverpool — iconic in the comeback vs AC Milan',
 'One-club career at Liverpool — 737 appearances over 17 years',
 'Now one of football''s most respected TV pundits alongside Gary Neville',
 82.00, FALSE),

('Robbie Fowler',
 '1975-04-09', 'Aries', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Liverpool', 'Leeds United', 'Manchester City', 'Blackburn Rovers'],
 ARRAY['Retired'], ARRAY['Centre Forward'],
 'Scored a hat-trick vs Arsenal in 1994 in just 4 minutes 33 seconds',
 'Liverpool icon — nicknamed "God" by the Anfield faithful',
 '183 career goals — one of the most prolific English strikers of his generation',
 81.00, FALSE),

('Michael Owen',
 '1979-12-14', 'Sagittarius', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Liverpool', 'Real Madrid', 'Newcastle United', 'Manchester United'],
 ARRAY['Retired'], ARRAY['Forward'],
 'Won the Ballon d''Or in 2001 — last English player to win it',
 'Iconic solo goal vs Argentina at the 1998 World Cup aged just 18',
 'Scored a 93rd-minute hat-trick winner for Man Utd vs Man City in 2009',
 85.00, FALSE),

('Luis Suarez',
 '1987-01-24', 'Aquarius', 'Footballer', 'Premier League', 'Uruguayan', 'Male',
 ARRAY['Uruguayan'],
 ARRAY['Liverpool', 'Barcelona', 'Ajax', 'Atletico Madrid', 'Nacional'],
 ARRAY['Active'], ARRAY['Forward'],
 'Scored 31 Premier League goals in 2013–14 — PL Golden Boot winner',
 'Bit opponents on three separate occasions — bans totalling 19 matches',
 'Led Liverpool to within touching distance of their first PL title in 2013–14',
 88.00, TRUE),

('Mohamed Salah',
 '1992-06-15', 'Gemini', 'Footballer', 'Premier League', 'Egyptian', 'Male',
 ARRAY['Egyptian'],
 ARRAY['Liverpool', 'Chelsea', 'Roma', 'Fiorentina'],
 ARRAY['Active'], ARRAY['Forward', 'Right Winger'],
 'Set PL single-season scoring record with 32 goals in 2017–18',
 '2019 UEFA Champions League winner with Liverpool',
 'Africa''s all-time leading PL goalscorer',
 96.00, TRUE),

('Sadio Mane',
 '1992-04-10', 'Aries', 'Footballer', 'Premier League', 'Senegalese', 'Male',
 ARRAY['Senegalese'],
 ARRAY['Liverpool', 'Southampton', 'RB Salzburg', 'Bayern Munich', 'Al-Nassr'],
 ARRAY['Active'], ARRAY['Forward', 'Left Winger'],
 '2019 Champions League and 2020 Premier League winner with Liverpool',
 'African Player of the Year in 2022 — helped Senegal win their first AFCON',
 'Premier League Golden Boot joint winner 2021–22 with Salah and Son',
 88.00, TRUE),

('Roberto Firmino',
 '1991-10-02', 'Libra', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 ARRAY['Brazilian'],
 ARRAY['Liverpool', 'Hoffenheim', 'Al-Ahli'],
 ARRAY['Active'], ARRAY['Forward', 'False Nine'],
 '2019 Champions League and 2020 Premier League winner with Liverpool',
 'The creative engine of Klopp''s famous Liverpool front three',
 'Rarely used a shin pad — famous for his showboating no-look finishes',
 83.00, TRUE),

('Virgil van Dijk',
 '1991-07-08', 'Cancer', 'Footballer', 'Premier League', 'Dutch', 'Male',
 ARRAY['Dutch'],
 ARRAY['Liverpool', 'Southampton', 'Celtic', 'Groningen'],
 ARRAY['Active'], ARRAY['Centre Back'],
 'Ballon d''Or runner-up in 2019 — considered the world''s best defender',
 '2019 Champions League and 2020 Premier League winner with Liverpool',
 '£75m transfer from Southampton in 2018 — then a world record for a defender',
 91.00, TRUE),

('Alisson Becker',
 '1992-10-02', 'Libra', 'Footballer', 'Premier League', 'Brazilian', 'Male',
 ARRAY['Brazilian'],
 ARRAY['Liverpool', 'Roma'],
 ARRAY['Active'], ARRAY['Goalkeeper'],
 '2019 Champions League winner — awarded the CL Golden Glove',
 'Scored a header vs West Brom in May 2021 to keep Liverpool''s top-four hopes alive',
 '2020 Premier League winner with Liverpool',
 88.00, TRUE),

('Trent Alexander-Arnold',
 '1998-10-07', 'Libra', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Liverpool'],
 ARRAY['Active'], ARRAY['Right Back', 'Midfielder'],
 'Whipped quick corner to Origi vs Barcelona in 2019 CL semi-final — turned the tie',
 'Most assists ever recorded by a defender in Premier League history',
 '2019 Champions League and 2020 Premier League winner with Liverpool',
 89.00, TRUE),

('Xabi Alonso',
 '1981-11-25', 'Sagittarius', 'Footballer', 'Premier League', 'Spanish', 'Male',
 ARRAY['Spanish', 'Basque'],
 ARRAY['Liverpool', 'Real Madrid', 'Bayern Munich', 'Real Sociedad'],
 ARRAY['Retired'], ARRAY['Midfielder', 'Defensive Midfielder'],
 'Scored the equaliser in the 2005 Champions League final — penalty rebound in extra time',
 '2010 World Cup and 2008/2012 Euros winner with Spain',
 'Became one of Europe''s most admired managers at Bayer Leverkusen post-retirement',
 87.00, FALSE),

('Fernando Torres',
 '1984-03-20', 'Pisces', 'Footballer', 'Premier League', 'Spanish', 'Male',
 ARRAY['Spanish'],
 ARRAY['Liverpool', 'Chelsea', 'Atletico Madrid', 'AC Milan'],
 ARRAY['Retired'], ARRAY['Centre Forward'],
 'Scored 24 Premier League goals in debut Liverpool season 2007–08 — sensational',
 'Iconic winner vs Germany in Euro 2008 final — the defining moment of his career',
 '£50m transfer to Chelsea in January 2011 — a British transfer record at the time',
 86.00, FALSE),

-- ─── CHELSEA LEGENDS ──────────────────────────────────────────────────────────

('Frank Lampard',
 '1978-06-20', 'Gemini', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Chelsea', 'West Ham United', 'Manchester City', 'New York City FC'],
 ARRAY['Retired'], ARRAY['Midfielder'],
 'Chelsea''s all-time top scorer with 211 goals',
 '2012 UEFA Champions League winner — scored in the final',
 'Three Premier League titles and named BBC Sports Personality of the Year 2005',
 91.00, FALSE),

('John Terry',
 '1980-12-07', 'Sagittarius', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Chelsea', 'Aston Villa'],
 ARRAY['Retired'], ARRAY['Centre Back'],
 'Five Premier League titles as Chelsea captain',
 'Slipped taking his penalty in the 2008 CL final shootout — cost Chelsea the trophy',
 'Led Chelsea to their first ever Champions League title in 2012',
 88.00, FALSE),

('Petr Cech',
 '1982-05-20', 'Taurus', 'Footballer', 'Premier League', 'Czech', 'Male',
 ARRAY['Czech'],
 ARRAY['Chelsea', 'Arsenal', 'Rennes'],
 ARRAY['Retired'], ARRAY['Goalkeeper'],
 'Premier League all-time clean sheet record — 202 across his career',
 '2012 Champions League winner with Chelsea',
 'Wore a protective headgear for the rest of his career after a fractured skull in 2006',
 87.00, FALSE),

('Didier Drogba',
 '1978-03-11', 'Pisces', 'Footballer', 'Premier League', 'Ivorian', 'Male',
 ARRAY['Ivorian'],
 ARRAY['Chelsea', 'Galatasaray', 'Shanghai Shenhua', 'Montreal Impact'],
 ARRAY['Retired'], ARRAY['Centre Forward'],
 'Scored 88th-minute equaliser then converted winning penalty in 2012 CL final',
 'Four FA Cup winner''s medals with Chelsea — a club record',
 'Chelsea''s second all-time top scorer with 164 goals',
 90.00, FALSE),

('Eden Hazard',
 '1991-01-07', 'Capricorn', 'Footballer', 'Premier League', 'Belgian', 'Male',
 ARRAY['Belgian'],
 ARRAY['Chelsea', 'Real Madrid', 'Lille'],
 ARRAY['Retired'], ARRAY['Forward', 'Left Winger', 'Attacking Midfielder'],
 'Two Premier League titles with Chelsea — PFA Player of the Year twice',
 'Moved to Real Madrid for £130m in 2019 — never replicated his Chelsea form',
 'Chelsea''s most creative player of the 2010s — beloved at Stamford Bridge',
 89.00, FALSE),

('Ashley Cole',
 '1980-12-20', 'Sagittarius', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Arsenal', 'Chelsea', 'Crystal Palace', 'Roma'],
 ARRAY['Retired'], ARRAY['Left Back'],
 'Seven FA Cup winner''s medals — the most by any player in history',
 '2012 Champions League winner with Chelsea',
 'Left Arsenal for Chelsea in controversial circumstances — nicknamed "Cashley Cole"',
 84.00, FALSE),

('N''Golo Kante',
 '1991-03-29', 'Aries', 'Footballer', 'Premier League', 'French', 'Male',
 ARRAY['French', 'Malian'],
 ARRAY['Leicester City', 'Chelsea', 'Al-Ittihad'],
 ARRAY['Active'], ARRAY['Defensive Midfielder', 'Central Midfielder'],
 'Won the Premier League with Leicester (2016) and Chelsea (2017) in consecutive seasons',
 '2018 FIFA World Cup winner with France',
 'Covered more ground than almost any other player in PL history — ran for two men',
 88.00, TRUE),

('Cole Palmer',
 '2002-05-06', 'Taurus', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Chelsea', 'Manchester City'],
 ARRAY['Active'], ARRAY['Attacking Midfielder', 'Forward', 'Winger'],
 'Chelsea''s standout performer in 2023–24 — most goals and assists in the squad',
 'England breakthrough at Euro 2024 — scored crucial goals off the bench',
 'Released by Man City then became one of the PL''s best players at Chelsea',
 86.00, TRUE),

-- ─── MANCHESTER CITY LEGENDS ──────────────────────────────────────────────────

('Sergio Aguero',
 '1988-06-02', 'Gemini', 'Footballer', 'Premier League', 'Argentine', 'Male',
 ARRAY['Argentine'],
 ARRAY['Manchester City', 'Atletico Madrid'],
 ARRAY['Retired'], ARRAY['Centre Forward'],
 '"Agueroooo!" — 93:20 goal vs QPR in May 2012 to win Man City their first PL title',
 'Premier League''s all-time top foreign scorer with 184 goals',
 'Five Premier League titles with Manchester City',
 93.00, FALSE),

('Yaya Toure',
 '1983-05-13', 'Taurus', 'Footballer', 'Premier League', 'Ivorian', 'Male',
 ARRAY['Ivorian'],
 ARRAY['Manchester City', 'Barcelona', 'Monaco', 'Olympiakos'],
 ARRAY['Retired'], ARRAY['Midfielder', 'Central Midfielder'],
 'Scored both goals in the 2011 FA Cup final — Man City''s first major trophy in 35 years',
 'Three Premier League titles with Manchester City',
 'Ran from his own half to score vs Spurs in the 2012 title run-in',
 86.00, FALSE),

('Vincent Kompany',
 '1986-04-10', 'Aries', 'Footballer', 'Premier League', 'Belgian', 'Male',
 ARRAY['Belgian', 'Congolese'],
 ARRAY['Manchester City', 'Anderlecht', 'Burnley'],
 ARRAY['Retired'], ARRAY['Centre Back'],
 'Thunderous 30-yard strike vs Leicester in May 2019 sealed Man City''s Premier League title',
 'Four Premier League titles as Manchester City captain',
 'Led Burnley to Championship promotion as player-manager in 2022–23',
 87.00, FALSE),

('David Silva',
 '1986-01-08', 'Capricorn', 'Footballer', 'Premier League', 'Spanish', 'Male',
 ARRAY['Spanish'],
 ARRAY['Manchester City', 'Valencia', 'Real Sociedad', 'Celta Vigo'],
 ARRAY['Retired'], ARRAY['Midfielder', 'Attacking Midfielder'],
 'Four Premier League titles with Manchester City — considered their greatest ever player',
 '2010 World Cup and 2008/2012 Euros winner with Spain',
 'Nicknamed "Merlin" and "El Mago" — 436 Man City appearances in 10 seasons',
 89.00, FALSE),

('Kevin De Bruyne',
 '1991-06-28', 'Cancer', 'Footballer', 'Premier League', 'Belgian', 'Male',
 ARRAY['Belgian'],
 ARRAY['Manchester City', 'Chelsea', 'Wolfsburg', 'Werder Bremen', 'Genk'],
 ARRAY['Active'], ARRAY['Midfielder', 'Attacking Midfielder'],
 'Set the PL record of 20 assists in a single season in 2019–20',
 'Six Premier League titles with Manchester City by 2024',
 '2023 Treble winner — PL, FA Cup and Champions League with Man City',
 95.00, TRUE),

('Erling Haaland',
 '2000-07-21', 'Cancer', 'Footballer', 'Premier League', 'Norwegian', 'Male',
 ARRAY['Norwegian'],
 ARRAY['Manchester City', 'Borussia Dortmund', 'RB Salzburg'],
 ARRAY['Active'], ARRAY['Centre Forward'],
 'Scored 36 Premier League goals in debut PL season 2022–23 — a new all-time record',
 '2023 Treble winner with Manchester City — PL, FA Cup, Champions League',
 '52 goals in all competitions in 2022–23 — a Manchester City club record',
 94.00, TRUE),

('Jack Grealish',
 '1995-09-10', 'Virgo', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English', 'Irish'],
 ARRAY['Manchester City', 'Aston Villa'],
 ARRAY['Active'], ARRAY['Winger', 'Attacking Midfielder'],
 '£100m signing for Manchester City in 2021 — British transfer record at the time',
 '2023 Treble winner with Man City — appeared at the final at Wembley and in Istanbul',
 'Former Aston Villa captain — beloved at Villa Park before the move',
 85.00, TRUE),

('Phil Foden',
 '2000-05-28', 'Gemini', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Manchester City'],
 ARRAY['Active'], ARRAY['Midfielder', 'Winger', 'Forward'],
 'PL Player of the Season 2023–24 — 19 goals and 8 assists in the league',
 'Man City academy product — never left the club, six Premier League titles',
 '2023 Treble winner — Champions League, PL and FA Cup with Man City',
 89.00, TRUE),

('Raheem Sterling',
 '1994-12-08', 'Sagittarius', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English', 'Jamaican'],
 ARRAY['Manchester City', 'Liverpool', 'Chelsea'],
 ARRAY['Active'], ARRAY['Forward', 'Winger'],
 'Five Premier League titles with Manchester City',
 'PFA Players'' Player of the Year 2019',
 'Moved to Chelsea for £47.5m in 2022 after winning everything with Man City',
 86.00, TRUE),

('Riyad Mahrez',
 '1991-02-21', 'Pisces', 'Footballer', 'Premier League', 'Algerian', 'Male',
 ARRAY['Algerian', 'French'],
 ARRAY['Manchester City', 'Leicester City', 'Al-Ahli'],
 ARRAY['Active'], ARRAY['Winger', 'Forward'],
 'PFA Players'' Player of the Year 2016 with title-winning Leicester City',
 'Three Premier League titles with Manchester City',
 'AFCON winner with Algeria in 2019 — scored five goals in the tournament',
 84.00, TRUE),

-- ─── PREMIER LEAGUE ICONS ─────────────────────────────────────────────────────

('Alan Shearer',
 '1970-08-13', 'Leo', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Newcastle United', 'Blackburn Rovers', 'Southampton'],
 ARRAY['Retired'], ARRAY['Centre Forward'],
 'Premier League all-time top scorer with 260 goals — a record that still stands',
 'Won the Premier League title with Blackburn Rovers in 1995',
 'Signed by hometown club Newcastle for then-world-record £15m in 1996',
 94.00, FALSE),

('Harry Kane',
 '1993-07-28', 'Leo', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Tottenham Hotspur', 'Bayern Munich', 'Leicester City', 'Millwall', 'Norwich City'],
 ARRAY['Active'], ARRAY['Centre Forward'],
 'Tottenham all-time top scorer — 280 goals in all competitions',
 'Three Premier League Golden Boots (2016, 2021, 2023)',
 'Moved to Bayern Munich for over £100m in 2023 — still seeking his first major trophy',
 93.00, TRUE),

('Jamie Vardy',
 '1987-01-11', 'Capricorn', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Leicester City', 'Fleetwood Town', 'Halifax Town'],
 ARRAY['Retired'], ARRAY['Centre Forward'],
 '2016 Premier League champion with Leicester City — the greatest upset in PL history',
 'Set PL record by scoring in 11 consecutive matches during the 2015–16 season',
 'Turned down Arsenal to stay at Leicester after winning the title',
 85.00, FALSE),

('Son Heung-min',
 '1992-07-08', 'Cancer', 'Footballer', 'Premier League', 'South Korean', 'Male',
 ARRAY['South Korean'],
 ARRAY['Tottenham Hotspur', 'Bayer Leverkusen', 'Hamburger SV'],
 ARRAY['Active'], ARRAY['Forward', 'Left Winger'],
 'Joint PL Golden Boot winner 2021–22 with 23 goals — shared with Mohamed Salah',
 'South Korea''s all-time top scorer and most capped outfield player',
 '2019 UEFA Champions League finalist with Spurs',
 88.00, TRUE),

('Mesut Ozil',
 '1988-10-15', 'Libra', 'Footballer', 'Premier League', 'German', 'Male',
 ARRAY['German', 'Turkish'],
 ARRAY['Arsenal', 'Real Madrid', 'Werder Bremen', 'Fenerbahce'],
 ARRAY['Retired'], ARRAY['Attacking Midfielder'],
 '2014 FIFA World Cup winner with Germany',
 'Arsenal''s creative No.10 for seven years — regular provider of assists',
 'Retired from international football in 2018 citing racism from the German FA',
 85.00, FALSE),

('Dennis Bergkamp',
 '1969-05-10', 'Taurus', 'Footballer', 'Premier League', 'Dutch', 'Male',
 ARRAY['Dutch'],
 ARRAY['Arsenal', 'Inter Milan', 'Ajax'],
 ARRAY['Retired'], ARRAY['Forward', 'Attacking Midfielder'],
 'Iconic goal vs Argentina at 1998 World Cup — voted FIFA goal of the year',
 'Refused to fly — nicknamed The Non-Flying Dutchman',
 'Three Premier League titles and two FA Cups with Arsenal',
 88.00, FALSE),

('Alexander Isak',
 '1999-09-21', 'Virgo', 'Footballer', 'Premier League', 'Swedish', 'Male',
 ARRAY['Swedish'],
 ARRAY['Newcastle United', 'Real Sociedad', 'Borussia Dortmund', 'AIK'],
 ARRAY['Active'], ARRAY['Centre Forward'],
 'Newcastle''s key striker — signed for £63m in 2022 and quickly became a fan favourite',
 'Consistent Premier League performer with goals across both of his full seasons',
 'Sweden''s first-choice striker — among the most clinical forwards in Europe',
 82.00, TRUE),

('Ollie Watkins',
 '1995-12-30', 'Capricorn', 'Footballer', 'Premier League', 'English', 'Male',
 ARRAY['English'],
 ARRAY['Aston Villa', 'Brentford', 'Exeter City'],
 ARRAY['Active'], ARRAY['Centre Forward'],
 'Late winner vs Netherlands in Euro 2024 semi-final — sent England to the final',
 'Scored 19 Premier League goals for Aston Villa in 2023–24 — a career best',
 'Non-league to Premier League journey — started at Exeter City in League Two',
 83.00, TRUE);
